<?php if(!empty($flashMessages)){ ?>
<div class="alert alert-success fade in modal-content custom-success-content">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<?php foreach($flashMessages as $flashMessage){ ?>
			    <?php echo $flashMessage; } ?>
		</div>	
		
<?php } ?>            
                        <?php if($tabSelected == '#customer-details'){

                        	$form->setAttribute('action', $this->url('user/csrCustomerEdit', array('controller' => 'user', 'action' => 'csr-customer-detail', 'id' => $customerId)));
$form->setAttribute('id', 'customer-edit-form');
$form->setAttribute('class', 'announcement-search-form margin-top10 margin-bottom8');

 $form->setAttribute('onsubmit', 'return LoadAjaxDataTabs("", "1")');

$form->prepare();
echo $this->form()->openTag($form);
 ?>
							<div class="ordering-option padding8 margin-top30">
<!-- 								<h2 class="heading">Polar Link Customer:</h2> -->
								<?php if(!empty($errorMessage)){ ?>
<div class="alert alert-danger fade in margin-top20 margin-bottom0">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				    <?php echo $errorMessage; ?>
		</div>	
		
<?php } ?>
								<div class="col-md-12 form-signin login-form information-form text-center-responsive">
									<div class="col-md-6 left-top-block-feild">
										<fieldset class="col-md-12">
										<label for="inputEmail">Customer Group :</label> 
										<span class="user_edit_text"><?php 
													$valGroup = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_CUST_GRP'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_CUST_GRP'] ) : '');
													echo $this->formRow( $form->get('csr_cust_group')->setValue($valGroup));				
													
													echo $valGroup;
												?>
										</span>
										</fieldset>
										
										<fieldset class="col-md-12">
											<label for="inputEmail">Name for PolarLink :</label>
											<span class="hidden"> 
											<?php  
												$valName = $form->getInputFilter ()->getValue ( 'csr_user_name' ); // die;
												if (empty ( $formData ) && !empty($plinkCsrCustomerDetail ['output'])) {
													$valName = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_CUST_NAME'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_CUST_NAME'] ) : '');
												}
												$ele = $form->get ( 'csr_user_name' );
												$ele->setValue($valName);
												echo $this->formRow ( $ele );
											 ?>
											 </span>
											<span class="user_edit_text">
												<?php echo $valName; ?>
											</span>
											
										</fieldset>
										<fieldset class="col-md-12">
											<label>PolarLink Status :</label>
											<span class="hidden"> 
											<?php 
											$valStatus = $form->getInputFilter ()->getValue ( 'csr_status' ); // die;
											if (empty ( $formData ) && !empty($plinkCsrCustomerDetail ['output'])) {
												$valStatus = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_STATUS'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_STATUS'] ) : '');
											}
											$ele = $form->get ( 'csr_status' );
											$ele->setValue($valStatus);
											echo $this->formRow ( $ele );
											?>
											 </span>
											<span class="user_edit_text">
												<?php echo ($valStatus == 'E')?'Enabled':'Disabled'; ?>
											</span>
										</fieldset>
									</div>
									<div class="col-md-6">
<?php 
// $PLC_CRT_DATE = $PLC_CHG_DATE = $PLC_1ST_USE_DATE = $PLC_LAST_USE_DATE = '0001-01-01';

 	$PLC_CRT_DATE =  (!empty($plinkCsrCustomerDetail['output']['PLC_CRT_TIME'])?$this->date_helper($plinkCsrCustomerDetail['output']['PLC_CRT_TIME'], 'Y-m-d'):'0001-01-01');

 	$PLC_CHG_DATE = (!empty($plinkCsrCustomerDetail['output']['PLC_CHG_TIME'])?$this->date_helper($plinkCsrCustomerDetail['output']['PLC_CHG_TIME'], 'Y-m-d'):'0001-01-01');
 	$PLC_1ST_USE_DATE = (!empty($plinkCsrCustomerDetail['output']['PLC_1ST_USE'])?$this->date_helper($plinkCsrCustomerDetail['output']['PLC_1ST_USE'], 'Y-m-d'):'0001-01-01');
	$PLC_LAST_USE_DATE = (!empty($plinkCsrCustomerDetail['output']['PLC_LAST_USE'])?$this->date_helper($plinkCsrCustomerDetail['output']['PLC_LAST_USE'], 'Y-m-d'):'0001-01-01');

if($PLC_CRT_DATE == '0001-01-01') {
	$plinkCsrCustomerDetail['output']['PLC_CRT_TIME'] = '';
}
if($PLC_CHG_DATE == '0001-01-01') {
	$plinkCsrCustomerDetail['output']['PLC_CHG_TIME'] = '';
}
if($PLC_1ST_USE_DATE == '0001-01-01') {
	$plinkCsrCustomerDetail['output']['PLC_1ST_USE'] = '';
}
if($PLC_LAST_USE_DATE == '0001-01-01') {
	$plinkCsrCustomerDetail['output']['PLC_LAST_USE'] = '';
}



if(!empty($plinkCsrCustomerDetail['output']['PLC_CRT_TIME']) || !empty($plinkCsrCustomerDetail['output']['PLC_CHG_TIME']) || !empty($plinkCsrCustomerDetail['output']['PLC_1ST_USE']) || !empty($plinkCsrCustomerDetail['output']['PLC_LAST_USE'])){ ?>
									<div class="type-message right-top-block">
										
											<div class="UsersDefaults col-md-12 form-signin login-form information-form text-center-responsive">
												<div class="heading-activity">Customer Activity</div>
												<div class="clearfix"></div>
												<fieldset class="col-md-12">
													<label for="inputEmail">Added:</label> 
													<span class="normal-text"><?php if($plinkCsrCustomerDetail['output']['PLC_CRT_TIME']){ ?><?php  echo $this->date_helper($plinkCsrCustomerDetail['output']['PLC_CRT_TIME'], "M j, Y @ g:i a"); ?> <?php if(!empty(trim($plinkCsrCustomerDetail['output']['PLC_CRT_USER']))){ ?> by <?php echo $plinkCsrCustomerDetail['output']['PLC_CRT_USER']; } ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">Changed:</label> 
													<span class="normal-text"><?php if($plinkCsrCustomerDetail['output']['PLC_CHG_TIME']){ ?><?php  echo $this->date_helper($plinkCsrCustomerDetail['output']['PLC_CHG_TIME'], "M j, Y @ g:i a"); ?> <?php if(!empty(trim($plinkCsrCustomerDetail['output']['PLC_CHG_USER']))){ ?> by <?php echo $plinkCsrCustomerDetail['output']['PLC_CHG_USER']; } ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">First Login:</label> 
													<span class="normal-text"><?php if($plinkCsrCustomerDetail['output']['PLC_1ST_USE']){ ?><?php  echo $this->date_helper($plinkCsrCustomerDetail['output']['PLC_1ST_USE'],"M j, Y @ g:i a"); ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">Last Login:</label> 
													<span class="normal-text"><?php if($plinkCsrCustomerDetail['output']['PLC_LAST_USE']){ ?><?php  echo $this->date_helper($plinkCsrCustomerDetail['output']['PLC_LAST_USE'],"M j, Y @ g:i a"); ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
											</div>
											
										</div>
										<?php } ?>
									</div>
								</div>
								<div class="buttons">
				                <?php
				                echo $this->formRow ($form->get ( 'csr_customer_field'));
				                
				                echo $this->formButton($form->get('save'));
				                echo $this->formButton($form->get('Cancel'));
				                ?>
				
				                </div>
			 					<?php
									// echo $this->form()->closeTag();
								?>
								<div class="clearfix"></div>
							</div>
							<?php
									echo $this->form()->closeTag();
								?>
                       <?php } else if($tabSelected == '#customer-defaults'){ ?>
                        <div class="clearfix"></div>
                        <div class="margin-top10 margin-bottom20"><em>The information below will be the default selection for placing orders as this customer group, unless overriden by a user's defaults.</em></div>
                        <div class="clearfix"></div>
							<div class="ordering-option padding8 margin-top30 customer-defaults">
<!-- 								<h2 class="heading">Select Customer Defaults</h2> -->
								<div class="margin-top30">
								
								
								<?php $customerDefaultsForm->setAttribute('action', $this->url('user/csrCustomerEdit', array('controller' => 'user', 'action' => 'csr-customer-detail', 'id' => $customerId)));
								$customerDefaultsForm->setAttribute('id', 'customer-defaults-form');
								$customerDefaultsForm->setAttribute('class', 'col-md-12 form-signin login-form information-form margin-top0');
								$customerDefaultsForm->setAttribute('onsubmit', "return LoadAjaxDataTabs('', '1');");
								// $customerDefaultsForm->setAttribute('onsubmit', 'ChangeDirtyFlag(false)');								
								$customerDefaultsForm->prepare();
								echo $this->form()->openTag($customerDefaultsForm);
								
								/* commented by rohit for removing UOM all together
								?>
								<fieldset class="col-md-12">
								<?php $valPlcDefaultUom = $customerDefaultsForm->getInputFilter ()->getValue ( 'PLC_DFT_UOM' ); // die;
												
												if(empty($formData))
												{
													$valPlcDefaultUom = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_UOM'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_UOM'] ) : '');
													
												} else {
														$valPlcDefaultUom = $formData['PLC_DFT_UOM'];
												}
												
												?>
												<label for="PLC_DFT_UOM">Default Unit of Measure:</label>
												<?php 
													echo $this->formRow($customerDefaultsForm->get('PLC_DFT_UOM')->setAttribute('value', $valPlcDefaultUom)); 
												?>
											
		                        </fieldset>
		                        <?php  commented by rohit for removing UOM all together till here 
		                        */
		                        ?>
		                        <fieldset class="col-md-12">
		                        <?php $valPlcDefaultShipMethod = $customerDefaultsForm->getInputFilter ()->getValue ( 'PLC_DFT_SHIP_METHOD' ); // die;
												
												if(empty($formData))
												{
													$valPlcDefaultShipMethod = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_SHIP_METHOD'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_SHIP_METHOD'] ) : '');
													
												} else {
														$valPlcDefaultShipMethod = $formData['PLC_DFT_SHIP_METHOD'];
												}
												
												?>
												<label for="PLC_DFT_UOM">Default Shipping Method:</label>
												<?php 
													echo $this->formRow($customerDefaultsForm->get('PLC_DFT_SHIP_METHOD')->setAttribute('value', $valPlcDefaultShipMethod));
												?>
		                        </fieldset>
		                        
		                        <fieldset class="col-md-12">
										<label for="inputEmail">Default Ship-To:</label>
										<span class="normal-text width25per padding-none">
										<div class="customer-defaults-normal-text" id="defaultShipToCustNoShipNo">
										<?php 
										$trimmedDefaultCustNo = trim($plinkCsrCustomerDetail['output']['PLC_CUSTNO']);
										$trimmedDefaultShipTo = trim($plinkCsrCustomerDetail['output']['PLC_DFT_SHIPTO']);
										
										$showDefaultAddress = false;
										if(!empty($trimmedDefaultShipTo) && !empty($trimmedDefaultCustNo)) { 
											echo $trimmedDefaultCustNo.' / '.$trimmedDefaultShipTo;
											$showDefaultAddress = true;
										} else {
											echo 'No Default Ship-To Selected';
										}
 										?>
										</div>
										<a href="javascript:void(0)" id="change-text-icon" class="change-text" data-toggle="modal" data-target="#myModalShipTo">Select Ship-To</a>
										</span>
										<div class="col-md-6 col-sm-6 col-xs-12 width45per">
										<div id="CustomerDefaultAddressFull">
										<?php if($showDefaultAddress){ ?>
											<a href="javascript:void(0)" title="Clear selected Ship-To" alt="Clear selected Ship-To" class="customer_default_close" onclick="removeDefaultCustomerShipTo()"><i class="fa fa-times-circle">&nbsp;</i></a>
												<div class="customer_default_text height_inherit padt5">
											<?php 	
											
										if(!empty($customerShipTos['output'])){ 
										foreach($customerShipTos['output'] as $shipTo1){
													if(($trimmedDefaultShipTo == trim($shipTo1['ST_NUM'])) && ($trimmedDefaultCustNo == trim($shipTo1['ST_CUST']))){
															//		echo (trim($shipTo1['ST_NUM']).', '.trim($shipTo1['ST_NAME']));
															echo trim($shipTo1['ST_NAME']).'<br />';
															echo (!empty(trim($shipTo1['ST_ADR1']))?trim($shipTo1['ST_ADR1']).'<br />':'');
															echo (!empty(trim($shipTo1['ST_ADR2']))?trim($shipTo1['ST_ADR2']).'<br />':'');
															echo trim($shipTo1['ST_ADR3']).', '.trim($shipTo1['ST_STATE']).' - '.trim($shipTo1['ST_ZIP']);
													}
											}
										}
										
										?>
												</div>
												<?php } ?>
												</div>
											</div>
											<div class="clearfix"></div>
									</fieldset>
									<div class="clearfix"></div>
									<div class="buttons margin-top20 margin-bottom20">
									<?php
									
										echo $this->formRow($customerDefaultsForm->get('PLC_DFT_SHIPTO')->setAttribute('value', $plinkCsrCustomerDetail['output']['PLC_DFT_SHIPTO']));
										echo $this->formRow($customerDefaultsForm->get('PLC_CUSTNO')->setAttribute('value', $plinkCsrCustomerDetail['output']['PLC_CUSTNO']));
										
										echo $this->formRow($customerDefaultsForm->get('csr_customer_defaults'));
										echo $this->formButton($customerDefaultsForm->get('save'));
										echo $this->formButton($customerDefaultsForm->get('Cancel'));
										?>
					                </div>
			                		 <?php
										echo $this->form()->closeTag();

									?>
								
					
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="clearfix"></div>
							<div class="modal modal-shipTo" id="myModalShipTo" role="dialog">
							<div class="modal-dialog">
							<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Select Default Ship-To</h4>
      </div>
      <div class="modal-body">
								
									<div class="padding8">
										<div class="search-box searchBoxForShipTo margin-top10">
											
												<?php $shippingSearchForm->setAttribute('action', $this->url('user/csrCustomerDetail', array('controller' => 'user', 'action' => 'csr-customer-detail', 'id' => $customerId)));
								$shippingSearchForm->setAttribute('id', 'customer-search-shipping-form');
								// $shippingSearchForm->setAttribute('class', 'col-md-12 form-signin login-form information-form margin-top0');
								
								$shippingSearchForm->setAttribute('onsubmit', 'return AjaxSearchShipTos()');								
								$shippingSearchForm->prepare();
								echo $this->form()->openTag($shippingSearchForm);
							
                     
                     			echo $this->formRow($shippingSearchForm->get('SEARCHPARAMETER')); 
                     			echo $this->formRow($shippingSearchForm->get('SUBMIT'));                     
                     			echo $this->formRow($shippingSearchForm->get('searchshipping'));
                     			echo $this->formRow($shippingSearchForm->get('CUST_GROUP')->setValue($customerId));
                     			echo $this->form()->closeTag();
                     			?>
<!-- 												<input type="text" class="form-control pull-left" placeholder="search..." value="" />           -->
<!-- 												<button id="searchShipTo" class="customer-search"><i class="fa fa-search"></i></button> -->
<!-- 												<input type="hidden" name="searchshipping" value="search" /> -->
											                  
										</div>
<!-- 										<a class="clear-customer margin-top10" href="javascript:void(0)">Clear Filter</a> -->
										<div class="clearfix"></div>
										<div class="table-responsive selected-table dataForShipTos margin-bottom0">
											<section class="table-section">
												<div class="table-scroll">
													<table class="table-striped ship-order">
														<thead>
															<tr>
																<th>Cust.#CuCuCu<div>Cust.#</div></th>
																<th>Shp# ShShS<div>Shp#</div></th>
																<th>Ship To Name <div>Ship To Name</div></th>
																<th>Address <div>Address</div></th>
																<th>City <div>City</div></th>
																<th>State Sta<div>State</div></th>
																<th>Zip <div>Zip</div></th>
															</tr>
														</thead>
														<tbody  id="popUpDataShippingForm">
															<?php  if(!empty($customerShipTos['output'])){ 
																$showButtonsDefaultShipTo = true;
	                            	foreach($customerShipTos['output'] as $shipTo){
										$class = '';
										if(!empty($trimmedDefaultShipTo) && !empty($trimmedDefaultCustNo)) { 
													if(($trimmedDefaultShipTo == trim($shipTo['ST_NUM'])) && ($trimmedDefaultCustNo == trim($shipTo['ST_CUST']))){
																	$class = ' active';
													}
										}
										
										$combinedId = trim($shipTo['ST_NUM']).'_'.trim($shipTo['ST_CUST']);
	                            	?>
	                            	<tr class="shipToDefaultSelectable<?php echo $class; ?>" id="<?php echo 'stnum_'.$combinedId; ?>">
	                                    <td id="<?php echo 'customerName_'.$combinedId; ?>"><?php echo $shipTo['ST_CUST']; ?></td>
	                                    <td><?php echo $shipTo['ST_NUM']; ?></td>
	                                    <td id="<?php echo 'name_'.$combinedId; ?>"><?php echo $shipTo['ST_NAME']; ?></td>
	                                    <td id="<?php echo 'address_'.$combinedId; ?>"><?php
										$trimmedShipTo = trim($shipTo['ST_ADR2']);
	                                    echo $shipTo['ST_ADR1'].(!empty($trimmedShipTo)? ' - '.$trimmedShipTo:''); ?></td>
	                                    <td id="<?php echo 'city_'.$combinedId; ?>"><?php echo $shipTo['ST_ADR3']; ?></td>
	                                    <td id="<?php echo 'state_'.$combinedId; ?>"><?php echo $shipTo['ST_STATE']; ?></td>
	                                    <td id="<?php echo 'zip_'.$combinedId; ?>"><?php echo $shipTo['ST_ZIP']; ?><span id="<?php echo 'defaultShippingMethod_'.$combinedId; ?>" style="display: none;"><?php echo trim($shipTo['SHIP_METHOD']); ?></span></td>
	                                </tr>
	                            <?php 
	                            }
                            } else { 
									$showButtonsDefaultShipTo = false;
							?>
		                            <tr>
		                            	<td colspan="7">No Ship-To exists</td>
		                            </tr>
                            <?php } ?>
														</tbody>
													</table>
												</div>
											</section>
										</div>
										<?php if($showButtonsDefaultShipTo){ ?>
										<div class="margin-top20">
	                    <button onclick="return changeDefaultShipTo()" type="button" class="btn">Select Ship-To</button>
	                    <button onclick="$('#myModalShipTo').modal('toggle');" type="button" class="btn">Cancel Ship-To Selection</button>
	                    </div>
	                    <?php } ?>
									</div>
								</div>
								<div class="clearfix"></div>
								</div>
							</div>
							 </div>
                        <?php } ?>
             <?php if($setDirtyFlag){ ?>
             <script type="text/javascript">
             changeDirtyFlag(true);
             </script>
             	
             <?php } ?>
             <script type="text/javascript">
             $(document).ready(function(){
             $('.shipToDefaultSelectable').click(
               	  function() {
       					
       					$('.shipToDefaultSelectable').removeClass('active');
       					$(this).addClass('active');
       					
       				});
             });
             </script>