             <div class="csr col-md-12 col-sm-12 col-xs-12">
				<div class="csr-heading text-center">Announcement Search</div>
				<div class="clearfix"></div>
				<?php if(!empty($flashMessages)){ ?>
<div class="alert alert-success fade in modal-content custom-success-content">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<?php foreach($flashMessages as $flashMessage){ ?>
			    <?php echo $flashMessage; } ?>
		</div>	
		
<?php } ?>
                <div class="current-0rder-background ordering-option padding8">
                	<h2 class="heading">Filter Search</h2>
                    <div class="clearfix">&nbsp;</div>
						
						<?php $form->setAttribute('action', $this->url('user/csrAnnouncementSearch', array('controller' => 'user', 'action' => 'csr-announcement-search')));
$form->setAttribute('id', 'announcement-search-form');
$form->setAttribute('class', 'announcement-search-form margin-top10 margin-bottom8');

 $form->setAttribute('onsubmit', 'return validateCsrAnnouncementSearchForm()');

$form->prepare();
echo $this->form()->openTag($form);
 ?>
							<div class="col-md-12">
							<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per line-height-normal">Announcement Text:</label>
										<?php echo $this->formRow($form->get('ANNOUNCEMENT_TEXT'));  ?>
									</fieldset>
								</div>
								<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per">Facility:</label>
										 <?php echo $this->formRow($form->get('FACILITY')->setAttribute('options', $facilities));  ?>
									</fieldset>
								</div>
								<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per">Cust. Type:</label>
										<?php echo $this->formRow($form->get('CUST_TYPE')->setAttribute('options', $customerTypes));  ?>
									</fieldset>
								</div>
								
<!-- 								<div class="col-md-4 col-sm-6 col-xs-12 padding0"> -->
<!-- 									<fieldset> -->
<!-- 										<label class="width40per">Company:</label> -->
										<?php // echo $this->formRow($form->get('COMPANY'));  ?>
<!-- 									</fieldset> -->
<!-- 								</div> -->
							</div>
							
							<div class="col-md-12">
								
								<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per">Start Date:</label>
										<span class="calendar-field">
											<?php echo $this->formRow($form->get('START_DATE'));  ?>
											<!-- <span class="add-on icons" style="font-size:28px;">
					<i class="fa fa-calendar"></i>
					
						</span> -->
										</span>
									</fieldset>
								</div>
								<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per">End Date:</label>
										<span class="calendar-field">
															<?php echo $this->formRow($form->get('END_DATE'));  ?>
										
											<!-- <span class="add-on icons" style="font-size:28px;">
					<i class="fa fa-calendar"></i>
					
						</span>  -->
										</span>
									</fieldset>
								</div>
								<div class="col-md-4 col-sm-6 col-xs-12 padding0">
									<fieldset>
										<label class="width40per">
										
										<a href="javascript:void(0);" class="clear-customer margin-top0" onclick="clearForm(document.getElementById('announcement-search-form'));">Clear Filter</a>
										<!--  <input type="button" class="clear-customer margin-top0" onclick="clearForm(this.form);" value="Clear  Filter"> -->
										</label>
										<span class="selectedShipToButtons">
										
										 <?php echo $this->formButton($form->get('Search')); ?>
<!-- 											<button class="btn margin-right" type="submit" value="submit" name="save"><i class="fa fa-search"></i> -->
<!-- &nbsp;Search</button> -->
										</span>
									</fieldset>
								</div>
							</div>
							
							
							<div class="clearfix"></div>
							 <?php

echo $this->form()->closeTag();


?>
						
                    
                    <div class="clearfix"></div>
                </div>
				
				<div class="clearfix"></div>
				<p class="block-bottom-text">Select an Announcement below, then click button to view, change or delete the record.</p>
				<div class="clearfix"></div>
				<div class="current-0rder-background ordering-option padding8">
                	<h2 class="heading">Announcements Matching Search Filters</h2>
                    <div class="clearfix">&nbsp;</div>                    
                    <div class="table-responsive selected-table dataForShipTos">
                    	<section class="table-section">
  							<div class="table-scroll">
                        <table id="polarlink-announcements" class="table-striped ship-order">
                            <thead>
                                <tr>
                                    <th>Facility Fac<div>Facility</div></th>
									<th>Cust. TypeTypeTyp <div>Cust. Type</div></th>
									<th>Start Date <div>Start Date</div></th>
									<th>End Date <div>End Date</div></th>
									<th width="32%">Message <div>Message</div></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                            $showButtons = '';
                            
                            if(!empty($plinkAnnouncements['output'])){
								$showButtons = true;
								 // echo '<pre>'; print_r($plinkAnnouncements['output']); die;
                            	foreach($plinkAnnouncements['output'] as $plinkAnnouncement){ 
									$trimmedCustTypes = trim($plinkAnnouncement['PLA_CUST_TYPE']);
									 $trimmedFacility = trim($plinkAnnouncement['PLA_FACILITY']);
							  ?>
								<tr class="AnnouncementSelectable" id="<?php echo trim($plinkAnnouncement['PLA_ID']); ?>">
									<td><?php if(!empty($trimmedFacility) && isset($facilities[$trimmedFacility])){ echo trim($facilities[$trimmedFacility]); }else { echo '*All'; } ?></td>
									<td><?php if(!empty($trimmedCustTypes) && isset($customerTypes[$trimmedCustTypes])){ echo $customerTypes[$trimmedCustTypes]; } else { echo '*All'; }  ?></td>
									<td><?php // echo date("M j, Y", strtotime($plinkAnnouncement['PLA_START_DATE'])); 
							  				echo date("m/d/y", strtotime($plinkAnnouncement['PLA_START_DATE']));
							  				?></td>
									<td><?php // echo date("M j, Y", strtotime($plinkAnnouncement['PLA_END_DATE'])); 
							  				echo date("m/d/y", strtotime($plinkAnnouncement['PLA_END_DATE']));
							  				?></td>
									<td><?php echo $plinkAnnouncement['PLA_MESSAGE']; ?></td>
								</tr>
								<?php }
                            	
                            } else { 
							$showButtons = false;
							?>
                            <tr>
									<td colspan="5">No Announcement Exists</td>
									
								</tr>
								<?php } ?>
                            </tbody>
                        </table>
                    	</div>
                    	</section>
                    </div>
                    <div class="clearfix"></div>
					<div>
						<span class="selectedShipToButtons selectedShipToButtonsActions">
							<button id='add' type="button" class="btn margin-right"><i class="fa fa-plus-circle"></i>&nbsp;Add</button>
						</span>
						<span class="selectedShipToButtons selectedShipToButtonsActions">
							<button id='view' type="button" class="btn margin-right"><i class="fa fa-eye"></i>&nbsp;View</button>
						</span>
						<span class="selectedShipToButtons selectedShipToButtonsActions">
							<button id='edit' type="button" class="btn margin-right"><i class="fa fa-pencil"></i>&nbsp;Edit</button>
						</span>
						<span class="selectedShipToButtons selectedShipToButtonsActions">
							<button id='remove' type="button" class="btn"><i class="fa fa-times-circle"></i>&nbsp;Remove</button>
						</span>
					</div>
                               
                    
                    <div class="clearfix"></div>
                </div>
                
               
             </div>
             
             
          <link href="<?php echo $this->basepath('/css/jquery-ui.css'); ?>" media="screen" rel="stylesheet" type="text/css">
<script	src="<?php echo $this->basepath('/js/jquery-ui.js'); ?>"></script>   
<script type="text/javascript">
// When the document is ready
	$(function() {
	    $( "#start_date" ).datepicker({
	    	showOn: "button", 
    	    buttonText: "<span class='font-size28 add-on icons'><i class='fa fa-calendar'></i></span>",
	        defaultDate: "+1w",
	        changeMonth: false,
	        numberOfMonths: 1,
	        onClose: function( selectedDate ) {
	          $( "#end_date" ).datepicker( "option", "minDate", selectedDate );
	        }
	      });
	      $( "#end_date" ).datepicker({
    	  	showOn: "button", 
    	    buttonText: "<span class='font-size28 add-on icons'><i class='fa fa-calendar'></i></span>",
		    defaultDate: "+1w",
	        changeMonth: false,
	        numberOfMonths: 1,
	        onClose: function( selectedDate ) {
	          $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );
	        }
	      });
	});
</script>
             <script type="text/javascript">
             $(function(){
             $('.AnnouncementSelectable').click(
            			function() {
            			//	_isDirty = true;
            				$('.AnnouncementSelectable').removeClass('active');
            				$(this).addClass('active');
//              				$('.selectedShipToButtons').show();
            			});
 			$('.selectedShipToButtonsActions button').click(
					function() {
						var attId = $(this).attr('id');
						if(attId == 'add'){
							 window.location = "/user/csr-announcement-detail/"+attId;
							 return;
							}

						
						if($('.AnnouncementSelectable').hasClass('active')){
							var AnnouncementId = $('.AnnouncementSelectable.active').attr('id');
							
							if(attId != 'remove'){
							 window.location = "/user/csr-announcement-detail/"+attId+'/'+AnnouncementId;
							}

							if(attId == 'remove'){
								bootbox.confirm("Are you sure you want to delete this customer?", function( result){
									if(result == true){
									$('#loading-image').show();
									// sending the ajax request
								    $.ajax({
								        url: "/user/csr-announcement-detail/"+attId+'/'+AnnouncementId,
								        type: "POST",
								        data:  {},
								        dataType: "json",
								        async: false,
								        success: function(result) {
								        	if(result == 'success'){
									        	$('#'+AnnouncementId).remove();
									        	bootbox.alert('Announcement Removed Successfully');
								        	} else {
												alert(result);
								        	}
								        	 return false;
								            // do nothing here
								     
								        },
								        failure: function(errMsg) {
								            alert(errMsg);
								            return false;
								        },
								        complete: function (){
								        	$('#loading-image').hide();
								        }
								    });
									} else {
											//return false;					
										}

									 });
								
							}
						}else {
							bootbox.alert('Please select an announcement');
							
						}
					});
             });
             </script>