<div class="csr col-md-12 col-sm-12 col-xs-12">
	<div class="csr-heading text-center">PolarLink Customer Details</div>
	<div class="clearfix"></div>
	<!--  <h1 class="csr-top-link">Add a Customer <a href="<?php //echo $this->url('user/csrCustomerList'); ?>"><i class="fa fa-angle-left"></i>&nbsp;Back to List of Customers</a></h1> -->
	<h1 class="csr-top-link">Add a Customer <a href= "javascript:void(0)" onclick="return listingPages('csr-customer-list')"><i class="fa fa-angle-left"></i>&nbsp;Back to List of Customers</a></h1>	
		<div class="clearfix"></div>
		<p class="block-bottom-text  margin-top0">Fields marked with <sup class="colorred sup-top-bottom">*</sup> are required.</p>
		<div class="clearfix"></div>
    <div class="item-search-tabs click-btn-position margin-top20">
         <ul data-tabs="tabs" class="nav nav-tabs" id="tabs">
         	<li class="active"><a data-toggle="tab" href="#customer-details">Customer Details</a></li>
         </ul>
                    <div class="tab-content" id="my-tab-content">
                        <div id="customer-details" class="tab-pane active">
								<?php $form->setAttribute('action', $this->url('user/csrCustomerAdd', array('controller' => 'user', 'action' => 'csr-customer-add')));
									$form->setAttribute('id', 'customer-add-form');
									$form->setAttribute('class', 'announcement-search-form margin-top10 margin-bottom8');
									 // $form->setAttribute('onsubmit', 'return validateCsrAnnouncementSearchForm()');
									$form->prepare();
									echo $this->form()->openTag($form);
								 ?>
							<div class="ordering-option padding8 margin-top30">
								<!--  <h2 class="heading">Polar Link Customer:</h2>  -->
									<?php if(!empty($errorMessage)){ ?>
										<div class="alert alert-danger fade in margin-top20 margin-bottom0">
											<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
											<?php echo $errorMessage; ?>
										</div>
									<?php } ?>
								<div class="col-md-12 form-signin login-form information-form text-center-responsive">
								<p id="error_msg_if_any_found" style="padding-left:50px; color:red"></p>
									<div class="row" > <div class="col-md-12">
									<div class="col-md-6 left-top-block-feild">
										<fieldset class="col-xs-12">
										<label for="inputEmail">Customer Group<sup class="colorred sup-top-bottom">*</sup> :</label> 
										<?php echo $this->formRow( $form->get('csr_cust_group')); ?>
										
										</fieldset></div>
											<div class="col-xs-12 col-sm-4 col-md-2 continue_button_section"><button type="button" name="Cancel" class="btn" id="check-group-validation" onclick="return checkCustGroupvalidation()" value="">Continue...</button></div>
										</div></div>
										
										<div class="col-xs-12" id='show_rest_details' style="display:none">
									<div class="row">
										<div class="col-md-6 left-top-block-feild">
										
										<fieldset class="col-md-12">
											<label for="inputEmail">Name for PolarLink<sup class="colorred sup-top-bottom">*</sup> :</label> 
											<?php  
												echo $this->formRow ( $form->get ( 'csr_user_name' ) );
											 ?>
										</fieldset>
										<fieldset class="col-md-12">
											<label>PolarLink Status<sup class="colorred sup-top-bottom">*</sup>:</label>
											<?php 
												echo $this->formRow ( $form->get ( 'csr_status' ) );
							 				?>
										</fieldset>
									</div>
									<div class="col-md-6 col-sm-6 only_tablet">&nbsp;</div>
									<fieldset class="col-md-12 bottom-block-with-email"><label for="inputPassword">Email Address : <div class="label-small-text">to receive order notifications</div>
									<div style="color: #ff0000">Polar Use Only</div>
									</label>
										<span class="arae-error-message" style="height:inherit;">
											<?php  echo $this->formRow ( $form->get ( 'csr_email_address' ) ); ?>
										</span>
										<ul class="side-text">
										  <li>You can enter multiple email addresses (max 2500 characters).</li>
										  <li>Separate each email address by comma.</li>
										  
										</ul>
									</fieldset>
									<div class="col-md-6 left-top-block-feild">
									<?php /* <fieldset class="col-xs-12">
												<?php $valPlcDefaultUom = $form->getInputFilter ()->getValue ( 'PLC_DFT_UOM' ); 
												if(empty($valPlcDefaultUom)  && !$request->isPost ())
												{
													//$valPlcDefaultUom = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_UOM'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_UOM'] ) : '');
													
												} ?>
												<label for="PLC_DFT_UOM">Default UOM <sup class="colorred sup-top-bottom">*</sup>:</label>
												<?php echo $this->formRow($form->get('PLC_DFT_UOM')->setAttribute('value', $valPlcDefaultUom)); ?>	
										</fieldset> */ ?>
										<fieldset class="col-xs-12">
											<?php $valPlcDefaultShipMethod = $form->getInputFilter ()->getValue ( 'PLC_DFT_SHIP_METHOD' ); 
												if(empty($valPlcDefaultShipMethod)  && !$request->isPost ())
												{
													//$valPlcDefaultShipMethod = (! empty ( trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_SHIP_METHOD'] ) ) ? trim ( $plinkCsrCustomerDetail ['output'] ['PLC_DFT_SHIP_METHOD'] ) : '');
													
												} 
												?>
												<label for="PLC_DFT_UOM">Default Ship Method :</label>
												<?php echo $this->formRow($form->get('PLC_DFT_SHIP_METHOD')->setAttribute('value', $valPlcDefaultShipMethod));?>
										</fieldset>
										</div>
									
									<div class="col-xs-12">&nbsp;</div>
										<div class="col-xs-12">
											<div class="row">
												<div class="col-md-6 left-top-block-feild" >
													 <fieldset class="col-md-12">
														 <label for="inputEmail">Default Ship-To<sup class="colorred sup-top-bottom">*</sup>:</label>
															<span class="normal-text padding-none arae-error-message" style="padding:0px 0px;">
																<div class="customer-defaults-normal-text" id="defaultShipToCustNoShipNo">
																	<?php 
																	//$trimmedDefaultCustNo = trim($plinkCsrCustomerDetail['output']['PLC_CUSTNO']);
																//	$trimmedDefaultShipTo = trim($plinkCsrCustomerDetail['output']['PLC_DFT_SHIPTO']);
																	
																	$showDefaultAddress = false;
																	if(!empty($trimmedDefaultShipTo) && !empty($trimmedDefaultCustNo)) { 
																		echo $trimmedDefaultCustNo.' / '.$trimmedDefaultShipTo;
																		$showDefaultAddress = true;
																	} else {
																		echo '<p style="color:gray">'.'None Selected'.'</p>';
																	}
							 										?>
																</div>
																<div class="buttons margin-top20 margin-bottom20">
												<?php
													$valPLC_DFT_SHIPTO = $form->getInputFilter ()->getValue ( 'PLC_DFT_SHIPTO' );
													$valPLC_CUSTNO = $form->getInputFilter ()->getValue ( 'PLC_CUSTNO' );
													$valcsr_customer_defaults = $form->getInputFilter ()->getValue ( 'csr_customer_defaults' );										
													echo $this->formRow($form->get('PLC_DFT_SHIPTO')->setAttribute('value', $valPLC_DFT_SHIPTO));
													echo $this->formRow($form->get('PLC_CUSTNO')->setAttribute('value', $valPLC_CUSTNO));
													echo $this->formRow($form->get('csr_customer_defaults',$valcsr_customer_defaults));
												?>
											</div>
																<a href="javascript:void(0)" id="change-text-icon" class="change-text~ btn" data-toggle="modal" data-target="#myModalShipTo">Select Ship-To</a>
															</span>
															
													 </fieldset>
													 
												</div>
												<div class="col-xs-12 col-sm-6 col-md-6 content_sectiontablet">
																<div id="CustomerDefaultAddressFull">
																	<?php if($showDefaultAddress){ ?>
																		<a href="javascript:void(0)" class="customer_default_close" onclick="removeDefaultCustomerShipTo()"><i class="fa fa-times-circle">&nbsp;</i></a>
																			<div class="customer_default_text height_inherit">
																				<?php 
																					if(!empty($customerShipTos['output'])){ 
																					foreach($customerShipTos['output'] as $shipTo1){
																							if(($trimmedDefaultShipTo == trim($shipTo1['ST_NUM'])) && ($trimmedDefaultCustNo == trim($shipTo1['ST_CUST']))){
																											echo (trim($shipTo1['ST_NUM']).', '.trim($shipTo1['ST_NAME']));
																							}
																						}
																					}
																				?>
																			</div>
																			<?php } ?>
																</div>
															</div>
											</div>
										</div>
									
									<div class="buttons">
						                <?php
							                echo $this->formButton($form->get('save'));
							                echo $this->formButton($form->get('Cancel'));
						                ?>
					                </div>
									</div></div>
								</div>
								 <?php
										echo $this->form()->closeTag();
								?>
								<div class="clearfix"></div>
							</div>
                        </div>
					</div>
                </div>               
             </div>
          	<div class="modal modal-shipTo" id="myModalShipTo" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title">Select Default Ship-To</h4>
					       
					      </div>
								<div class="modal-body">
									<div class="padding8">
											<div class="search-box searchBoxForShipTo margin-top10">
												<?php $shippingSearchForm->setAttribute('action', $this->url('user/csrCustomerDetail', array('controller' => 'user', 'action' => 'csr-customer-detail')));
											$shippingSearchForm->setAttribute('id', 'customer-search-shipping-form');
											$shippingSearchForm->setAttribute('onsubmit', 'return AjaxSearchShipTos()');								
											$shippingSearchForm->prepare();
											echo $this->form()->openTag($shippingSearchForm);
			                     			echo $this->formRow($shippingSearchForm->get('SEARCHPARAMETER')); 
			                     			echo $this->formRow($shippingSearchForm->get('SUBMIT'));                     
			                     			echo $this->formRow($shippingSearchForm->get('searchshipping'));
			                     			echo $this->form()->closeTag();
			                     		?>
									</div>

								<div class="clearfix"></div>
								<div id="loading-image_popup"style="display:none;">
        <img src="/img/ajax-loader.gif"  >
</div>
								<div class="table-responsive selected-table dataForShipTos margin-bottom0">
									<section class="table-section">
										<div class="table-scroll">
											<table class="table-striped ship-order">
												<thead>
													<tr>
														<th>Cust.#CuCuCu<div>Cust.#</div></th>
														<th>Shp# ShShS<div>Shp#</div></th>
														<th>Ship To Name <div>Ship To Name</div></th>
														<th>Address <div>Address</div></th>
														<th>City <div>City</div></th>
														<th>State Sta<div>State</div></th>
														<th>Zip <div>Zip</div></th>
													</tr>
												</thead>
													<tbody  id="popUpDataShippingForm">
														<tr>
															<td colspan="7">No Ship-To exists</td>
														</tr>
													 </tbody>
											</table>
										</div>
									</section>
								</div>
									<div class="margin-top20">
										<button onclick="return changeDefaultShipTo()" type="button" class="btn">Select Ship-To</button>
										<button onclick="$('#myModalShipTo').modal('toggle');" type="button" class="btn">Cancel Ship-To Selection</button>
									</div>
							</div>
						</div>
								<div class="clearfix"></div>
								</div>
							</div>
							 </div>
          
          
          
          
          
          
          
          
          
          
          
             
         
<script>

	
		function checkCustGroupvalidation(){
		 var csr_cust_group = $.trim($('#csr_cust_group').val());
		 if(csr_cust_group!=''){
			 $('#loading-image').show();
		 $.ajax({
		        url: '/user/check-cust-group-validation',
		        type: "POST",
		        data:  {'csr_cust_group': csr_cust_group},
		     // dataType: "html",
		        async: false,
		        success: function(result) {
					var resMessageTrim = result.Message.trim();		       

		        	$('#remove_pre_error_cust').remove();
			       if(resMessageTrim !=''){

			    	   $("#show_rest_details").css("display", "none");
			       } else {
			    	   
			    	   $("#show_rest_details").css("display", "block");
			    	   $('#csr_cust_group').attr('readonly', true);
			    	   $('#check-group-validation').hide();
			    	   $( "#csr_user_name" ).focus();
				       }
					if($('#remove_pre_error_cust').length==1){
						$('#csr_cust_group').parent('.col-md-12').find('ul').html('<li>'+result.Message+'</li>');
				    }else{
				    	$('#csr_cust_group').addClass('input-error');
				    	$('#csr_cust_group').after('<ul id="remove_pre_error_cust"><li>'+result.Message+'</li></ul>');
					 }
		        	
		        	 return false;
		            // do nothing here
		     
		        },
		        failure: function(errMsg) {
		            alert(errMsg);
		            return false;
		        },
		        complete: function (){
		        	$('#loading-image').hide();
		        	return false;
		        }
		    });

		 }
			 
		}



$(document).ready(function() {
	$(document).on('click',".shipToDefaultSelectable",function () {
	    $(".shipToDefaultSelectable").removeClass("active");
	    // $(".tab").addClass("active"); // instead of this do the below 
	    $(this).addClass("active");   
	});

	 $( "#csr_cust_group" ).focus();

	 $('#csr_cust_group').keypress(function (e) {
		 var key = e.which;
		 if(key == 13)  // the enter key code
		  {
		    $('#check-group-validation').click();
		    return false;  
		  }
		});
		  


	$('#customer-add-form').on('submit',function(e){
		//e.preventDefault();
		var error = false;
		$('#csr_user_name').removeClass('input-error');
		$('#cust_user_err').remove();
		$('#cust_err').remove();
		$('#cust_err_email').remove();
		$('#cust_dft_uom').remove();
		$('#shipToPlcCustNo').removeClass('input-error');
		
		if($.trim($('#csr_user_name').val())==""){
			var msg = 'Name for Polarlink is required';
			$('#csr_user_name').addClass('input-error');
	    	$('#csr_user_name').after('<ul id="cust_user_err"><li>'+msg+'</li></ul>');
			error = true;
		}

		if($.trim($('#shipToPlcCustNo').val())=="" || $.trim($('#shipToPlcCustNo').val()) == "0"){
			//alert('Username is required');
			var msg1 = 'Default Ship-To is required';
			$('#shipToPlcCustNo').addClass('input-error');
	    	$('#shipToPlcCustNo').after('<ul id="cust_err"><li>'+msg1+'</li></ul>');
			error = true;
		}

		/* if($.trim($('#PLC_DFT_UOM').val())==""){
			//alert('Username is required');
			var msg1 = 'Default Unit of Measure';
			$('#PLC_DFT_UOM').addClass('input-error');
	    	$('#PLC_DFT_UOM').after('<ul id="cust_dft_uom"><li>'+msg1+'</li></ul>');
			error = true;
		} */
		if($.trim($('#csr_email_address').val() != ''))
		{

			var str = $.trim($('#csr_email_address').val());
				var emails = str.split(',');
				var invalidEmails = [];
				for (i = 0; i < emails.length; i++) { 
				    if(!validateEmail(emails[i].trim())) {
				      invalidEmails.push(emails[i].trim())
				    }
				}
				if(invalidEmails !=''){
					var msg1 = 'Invalid Emails <strong>'+invalidEmails+'</strong> Please correct them';
					$('#csr_email_address').addClass('input-error');
			    	$('#csr_email_address').after('<ul id="cust_err_email"><li>'+msg1+'</li></ul>');
					error = true;

					}

			}
		if(error){
			//alert('dsf');
			$('#error_msg_if_any_found').text('Changes not saved! Correct errors displayed below and try again');
			return false;
	     }else{
			return true;
		     }
		

		}); 





	    $('#myModalShipTo').on('shown.bs.modal', function (e) {
	   	 var cust_group_ship_to = $.trim($('#csr_cust_group').val());
		 if(cust_group_ship_to!=''){
		 $('#loading-image_popup').show();
		 $.ajax({
		        url: '/user/get-default-ship-to',
		        type: "POST",
		        data:  {'csr_cust_group': cust_group_ship_to},
		     // dataType: "html",
		        async: false,
		        success: function(result) {

			        
		        	$('#popUpDataShippingForm').empty();
			      if(result.html.output !=''){
				       $.each( result.html.output, function( i, val ) {
						var xc = '<tr class="shipToDefaultSelectable" id="stnum_'+val.ST_NUM+'_'+val.ST_CUST+'">'+
                            '<td id="customerName_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_CUST+'</td>'+
                            '<td>'+val.ST_NUM+'</td>'+
                            '<td id="name_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_NAME+'</td>'+
                            '<td id="address_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_ADR1+' </td>'+
                            '<td id="city_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_ADR3+'</td>'+
                           '<td id="state_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_STATE+'</td>'+
                            '<td id="zip_'+val.ST_NUM+'_'+val.ST_CUST+'">'+val.ST_ZIP+' <span id="defaultShippingMethod_'+val.ST_NUM+'_'+val.ST_CUST+'" style="display: none;">'+val.SHIP_METHOD+'</span></td>'+
                        '</tr>'; 
							$('#popUpDataShippingForm').append(xc);
			        	 
			        	}); 
			       } else {
			    	   			    	
			    	   var xc =   '<tr>'+'<td colspan="7">No Ship-To exists</td>'+' </tr>';
			    	  	 $('#popUpDataShippingForm').append(xc);
				       }
		        	 return false;
		            // do nothing here
		     
		        },
		        failure: function(errMsg) {
		            alert(errMsg);
		            return false;
		        },
		        complete: function (){
		        	$('#loading-image_popup').hide();
		        	return false;
		        }
		    });

		 }
	 })
	
	});






function changeDefaultShipTo(){
	 var idShipTo = false;
	 var combinedId = '';
	 if($('.ship-order').find('.active').length > 0){
		 idShipTo = $('.ship-order').find('.active').attr('id');
		// alert(idShipTo); return false;
	 }
	 if(idShipTo == false){
		bootbox.alert('Please Select a Ship To Address');
		return false;
	 }
	 
		idShipToArray = idShipTo.split('_');
		combinedId = idShipToArray['1'] + '_' + idShipToArray['2'];
		$('#CustomerDefaultAddressFull').html(
					'<a onclick="removeDefaultCustomerShipTo()" title="Clear selected Ship-To" alt="Clear selected Ship-To" class="customer_default_close" href="javascript:void(0)"><i class="fa fa-times-circle">&nbsp;</i></a><div class="customer_default_text height_inherit">'
				+ $('#name_' + combinedId).html() + '<br />'
				+ $('#address_' + combinedId).html() + '<br />'
				+ $('#city_' + combinedId).html() + ', '
				+ $('#state_' + combinedId).html() + ' - '
				+ $('#zip_' + combinedId).html()
				+ '</div>'
			);
		$('#shipToPlcCustNo').val(idShipToArray['2']);
		$('#shipToPlcDefault').val(idShipToArray['1']);
		$('#defaultShipToCustNoShipNo').html(idShipToArray['2'] + ' / ' + idShipToArray['1']);
		$('#myModalShipTo').modal('toggle');
		changeDirtyFlag(true);
return false;

}

function removeDefaultCustomerShipTo(){
		 bootbox.confirm("Are you sure, you want to clear the current ship To Address?", function( result){
				if(result == true){
					$('#CustomerDefaultAddressFull').html('');
					$('#shipToPlcCustNo').val('0');
					$('#shipToPlcDefault').val('0');
					$('#defaultShipToCustNoShipNo').html('No Default Ship-To Selected');
					changeDirtyFlag(true);
				
				} else {
						//return false;					
					}

				 });
}
function AjaxSearchShipTos(){

	//alert('kailash'); return false;
	 var searchShippingText = $('#searchShippingText').val().trim();
	 //alert(searchShippingText); return false;
	 var customerId = $('#csr_cust_group').val().trim();
	 $('#loading-image').show();
		// sending the ajax request
	    $.ajax({
	        url: '/user/ajax-search-ship-to',
	        type: "POST",
	        data:  {'search': searchShippingText, 'customerId' : customerId},
	     //   dataType: "html",
	        async: false,
	        success: function(result) {
	        	 $('#popUpDataShippingForm').html(result);
	        	 return false;
	            // do nothing here
	     
	        },
	        failure: function(errMsg) {
	            alert(errMsg);
	            return false;
	        },
	        complete: function (){
	        	$('#loading-image').hide();
	        	return false;
	        }
	    });
	    return false;
}

function validateEmail(email) {
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
}

/* $("#csr_cust_group").keyup(function(event){
    if(event.keyCode == 13){
        $("#check-group-validation").click();
    }
});
*/
</script>


