<?php // condition to check whether this is normal user or csr
$hideStatusAndType = false;
if($identity['PLU_POLAR_CSR'] == 'N' && $identity['PLU_PLINK_ADMIN'] == 'N'){
	$hideStatusAndType = true;
}
$adminUser = false;
if($identity['PLU_POLAR_CSR'] == 'N' && $identity['PLU_PLINK_ADMIN'] == 'Y'){
	$adminUser = true;
}
?>

<div class="csr col-md-12 col-sm-12 col-xs-12">
             	<div class="csr-heading text-center">PolarLink User Details</div>
				<div class="clearfix"></div>
				<h1 class="csr-top-link font20">
					<?php
					$valUserId = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_USER_ID'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_USER_ID'] ) : '');
					$valFirstName = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_FIRST_NAME'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_FIRST_NAME'] ) : '');
					$valLastName = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_LAST_NAME'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_LAST_NAME'] ) : '');
					?>
					User: <?php
					 if(!empty($valUserId)){
							 echo $valUserId.' - '; 
					} 
					if(!empty($valFirstName)){
					echo $valFirstName.' ';
					}
					if(!empty($valLastName)){
						echo $valLastName;
					}
					?>
					<?php if($hideStatusAndType){ ?>
					<a href="<?php echo $this->url('user'); ?>"><i class="fa fa-angle-left"></i>&nbsp;Back to Home Page</a>
					<?php } else { ?>
					<a href="javascript:void(0)"  onclick="return listingPages('csr-user-list')"  ><i class="fa fa-angle-left"></i>&nbsp;Back to List of Users</a>
					<?php } ?>
				</h1>
				<div class="clearfix"></div>
	<p class="block-bottom-text  margin-top0">Fields marked with <sup class="colorred sup-top-bottom">*</sup> are required.</p>
	<div class="clearfix"></div>
						
                <div class="item-search-tabs click-btn-position margin-top20">
                    <ul data-tabs="tabs" class="nav nav-tabs" id="tabs">
                        <li class="active"><a data-toggle="tab" href="#user-details">User Details</a></li>
                        <li><a data-toggle="tab" href="#user-defaults">User Defaults</a></li>
<!--                         <li><a data-toggle="tab" href="#users">Users</a></li> -->
                    </ul>
                    <div class="tab-content" id="my-tab-content">
                        <div id="user-details" class="tab-pane active">
                        <?php $form->setAttribute('action', $this->url('user/csrUserEdit', array('controller' => 'user', 'action' => 'csr-user-edit', 'id' => $userId)));
$form->setAttribute('id', 'user-edit-form');
$form->setAttribute('class', 'announcement-search-form margin-top10 margin-bottom8');

 $form->setAttribute('onsubmit', 'return LoadAjaxDataTabs("", "1")');

$form->prepare();
echo $this->form()->openTag($form);
 ?>
							<div class="ordering-option padding8 margin-top30">
<!-- 								<h2 class="heading">Polar Link Customer:</h2> -->
								<?php if(!empty($errorMessage)){ ?>
<div class="alert alert-danger fade in margin-top20 margin-bottom0">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				    <?php echo $errorMessage; ?>
		</div>	
		
<?php } ?>
								<div class="col-md-12 form-signin login-form information-form text-center-responsive">
									<div class="col-md-6 col-sm-12 col-xs-12 left-top-block-feild">
										<fieldset class="col-md-12">
										<label for="inputEmail">Customer Group :</label> 
										<span class="user_edit_text"><?php 
													$valGroup = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_CUST_GROUP'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_CUST_GROUP'] ) : '');
											//		echo $this->formRow( $form->get('PLU_CUST_GROUP')->setValue($valGroup));				
													
													echo $valGroup;
												?>
										</span>
										</fieldset>
										<fieldset class="col-md-12">
										<label for="inputEmail">User ID :</label> 
										<span class="user_edit_text"><?php 
													$valUserId = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_USER_ID'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_USER_ID'] ) : '');
													echo $this->formRow( $form->get('PLU_USER_ID')->setValue($valUserId));				
													
													echo $valUserId;
												?>
										</span>
										</fieldset>
										<fieldset class="col-md-12">
											<label for="inputEmail">First Name<sup class="colorred sup-top-bottom">*</sup> :</label> 
											<?php  
												$valFirstName = $form->getInputFilter ()->getValue ( 'PLU_FIRST_NAME' ); // die;
												if (empty ( $valFirstName ) && !empty($plinkCsrUserDetail ['output']) && !$request->isPost ()) {
													$valFirstName = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_FIRST_NAME'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_FIRST_NAME'] ) : '');
												}
												$ele = $form->get ( 'PLU_FIRST_NAME' );
												$ele->setValue($valFirstName);
												echo $this->formRow ( $ele );
											 ?>
											
										</fieldset>
										
										<fieldset class="col-md-12">
											<label for="inputEmail">Last Name<sup class="colorred sup-top-bottom">*</sup> :</label> 
											<?php  
												$valLastName = $form->getInputFilter ()->getValue ( 'PLU_LAST_NAME' ); // die;
												if (empty ( $valLastName ) && !empty($plinkCsrUserDetail ['output']) && !$request->isPost ()) {
													$valLastName = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_LAST_NAME'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_LAST_NAME'] ) : '');
												}
												$ele = $form->get ( 'PLU_LAST_NAME' );
												$ele->setValue($valLastName);
												echo $this->formRow ( $ele );
											 ?>
											
										</fieldset>
										
										<div class="clearfix"></div>
										</div>
									<div class="col-md-6">
<?php 
// $PLC_CRT_DATE = $PLC_CHG_DATE = $PLC_1ST_USE_DATE = $PLC_LAST_USE_DATE = '0001-01-01';

 	$PLU_CRT_DATE =  (!empty($plinkCsrUserDetail['output']['PLU_CRT_TIME'])?$this->date_helper($plinkCsrUserDetail['output']['PLU_CRT_TIME'], 'Y-m-d'):'0001-01-01');

 	$PLU_CHG_DATE = (!empty($plinkCsrUserDetail['output']['PLU_CHG_TIME'])?$this->date_helper($plinkCsrUserDetail['output']['PLU_CHG_TIME'], 'Y-m-d'):'0001-01-01');
 	$PLU_1ST_USE_DATE = (!empty($plinkCsrUserDetail['output']['PLU_1ST_USE'])?$this->date_helper($plinkCsrUserDetail['output']['PLU_1ST_USE'], 'Y-m-d'):'0001-01-01');
	$PLU_LAST_USE_DATE = (!empty($plinkCsrUserDetail['output']['PLU_LAST_USE'])?$this->date_helper($plinkCsrUserDetail['output']['PLU_LAST_USE'], 'Y-m-d'):'0001-01-01');

if($PLU_CRT_DATE == '0001-01-01') {
	$plinkCsrUserDetail['output']['PLU_CRT_TIME'] = '';
}
if($PLU_CHG_DATE == '0001-01-01') {
	$plinkCsrUserDetail['output']['PLU_CHG_TIME'] = '';
}
if($PLU_1ST_USE_DATE == '0001-01-01') {
	$plinkCsrUserDetail['output']['PLU_1ST_USE'] = '';
}
if($PLU_LAST_USE_DATE == '0001-01-01') {
	$plinkCsrUserDetail['output']['PLU_LAST_USE'] = '';
}



if(!empty($plinkCsrUserDetail['output']['PLU_CRT_TIME']) || !empty($plinkCsrUserDetail['output']['PLU_CHG_TIME']) || !empty($plinkCsrUserDetail['output']['PLU_1ST_USE']) || !empty($plinkCsrUserDetail['output']['PLU_LAST_USE'])){ ?>
									<div class="type-message right-top-block">
										
											<div class="UsersDefaults col-md-12 form-signin login-form information-form text-center-responsive">
												<div class="heading-activity">User Activity</div>
												<div class="clearfix"></div>
												<fieldset class="col-md-12">
													<label for="inputEmail">Added:</label> 
													<span class="normal-text"><?php if($plinkCsrUserDetail['output']['PLU_CRT_TIME']){ ?><?php  echo $this->date_helper($plinkCsrUserDetail['output']['PLU_CRT_TIME'], "M j, Y @ g:i a"); ?> <?php if(!empty(trim($plinkCsrUserDetail['output']['PLU_CRT_USER']))){ ?> by <?php echo $plinkCsrUserDetail['output']['PLU_CRT_USER']; } ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">Changed:</label> 
													<span class="normal-text"><?php if($plinkCsrUserDetail['output']['PLU_CHG_TIME']){ ?><?php  echo $this->date_helper($plinkCsrUserDetail['output']['PLU_CHG_TIME'], "M j, Y @ g:i a"); ?> <?php if(!empty(trim($plinkCsrUserDetail['output']['PLU_CHG_USER']))){ ?> by <?php echo $plinkCsrUserDetail['output']['PLU_CHG_USER']; } ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">First Login:</label> 
													<span class="normal-text"><?php if($plinkCsrUserDetail['output']['PLU_1ST_USE']){ ?><?php  echo $this->date_helper($plinkCsrUserDetail['output']['PLU_1ST_USE'],"M j, Y @ g:i a"); ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
												
												<fieldset class="col-md-12">
													<label for="inputEmail">Last Login:</label> 
													<span class="normal-text"><?php if($plinkCsrUserDetail['output']['PLU_LAST_USE']){ ?><?php  echo $this->date_helper($plinkCsrUserDetail['output']['PLU_LAST_USE'],"M j, Y @ g:i a"); ?><?php } else {echo '-'; } ?></span>
												</fieldset>
												
											</div>
											
										</div>
										<?php } ?>
									</div>
									<div class="clearfix"> </div>
									<div class="col-md-6 left-top-block-feild">
									<fieldset class="col-md-12">
										<label for="inputEmail">Password :</label>
										<span class="user_edit_text change-password-link"> 
											<a href="javascript:void(0)" id="change-text-icon" onclick="changePasswordOpen()">Change Password</a>
											<?php echo $this->formRow($form->get ( 'csr_change_pwd' ));
										//			echo $this->formRow($form->get ( 'PLU_PASSWORD' )->setValue(trim ( $plinkCsrUserDetail ['output'] ['PLU_PASSWORD'] )));
											?>
										</span>
										</fieldset>
										</div>
										<div class="clearfix"> </div>
										<div class="col-md-7 col-md-offset-2 col-xs-12 col-xs-offset-0">
										<span class="change-password-block" style="display:none;">
										<div class="change_password_toggle">
										<div class="close_icon"><a href="javascript:void(0)" onclick="changePasswordOpen()"><i class="fa fa-times"></i></a></div>									
										<fieldset class="col-md-12">
										<label for="plu_new_password">New Password<sup class="colorred sup-top-bottom">*</sup> :</label>
										
											<?php echo $this->formRow($form->get ( 'PLU_NEW_PASSWORD' ));?>
										</fieldset>
										
										<fieldset class="col-md-12">
										<label for="plu_confirm_password">Confirm New Password<sup class="colorred sup-top-bottom">*</sup> :</label>
										
											<?php echo $this->formRow($form->get ( 'PLU_CONFIRM_PASSWORD' ));?>
										</fieldset>
										</div>
										</span>
										</div>
										<div class="clearfix"> </div>
										
										<div class="col-md-6 left-top-block-feild">
										<fieldset class="col-md-12">
											<label>Status<sup class="colorred sup-top-bottom">*</sup> :</label>
											<?php 
											$valStatus = $form->getInputFilter ()->getValue ( 'PLU_STATUS' ); // die;
											if (empty ( $valStatus ) && !empty($plinkCsrUserDetail ['output'])  && !$request->isPost ()) {
												$valStatus = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_STATUS'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_STATUS'] ) : '');
											}
											
											
											
											$ele = $form->get ( 'PLU_STATUS' );
											 if($hideStatusAndType){ $ele->setAttribute('class', 'hidden');
													if($valStatus == 'E'){
														echo '<span class="user_edit_text">Enabled</span>';
													} else {
														echo '<span class="user_edit_text">Disabled</span>';
													}

											 }
											$ele->setValue($valStatus);
											echo $this->formRow ( $ele );
							
							
							 ?>
										</fieldset>
										<fieldset class="col-md-12">
											<label for="plu_email_address">Email Address<sup class="colorred sup-top-bottom">*</sup> : </label>
										<?php  
												$valEmail = $form->getInputFilter ()->getValue ( 'PLU_EMAIL_ADDRESS' ); // die;
												
												if(empty($valEmail)  && !$request->isPost ())
												{
													$valEmail = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_EMAIL_ADDRESS'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_EMAIL_ADDRESS'] ) : '');
													
												}
												$ele = $form->get ( 'PLU_EMAIL_ADDRESS' );
												$ele->setValue($valEmail);
												echo $this->formRow ( $ele ); 
												
												?>
									</fieldset>
									
									
									
									</div>
									<div class="col-md-6 left-top-block-feild">&nbsp;</div>
									<div class="clearfix"> </div>
									<div class="col-md-10 <?php if($hideStatusAndType){ echo 'hidden'; }?>">	 
									<fieldset class="col-md-12 csr-user-type-radio csr-user-edit">
								<label for="plu_user_type">User Type<sup class="colorred sup-top-bottom">*</sup> :</label>
								<?php
								$valUserType = $form->getInputFilter ()->getValue ( 'PLU_USER_TYPE' ); // die;
								
								if(empty($valUserType)  && !$request->isPost ())
								{
									if($plinkCsrUserDetail ['output'] ['PLU_POLAR_CSR'] == 'Y'){
										$valUserType = 'csr';
									} else if($plinkCsrUserDetail ['output'] ['PLU_PLINK_ADMIN'] == 'Y'){
										$valUserType = 'admin';
									} else{
										$valUserType = 'normal';
									} 
									// $valUserType = (! empty ( trim ( $plinkCsrUserDetail ['output'] ['PLU_EMAIL_ADDRESS'] ) ) ? trim ( $plinkCsrUserDetail ['output'] ['PLU_EMAIL_ADDRESS'] ) : '');
										
								}
								
								$ele = $form->get ( 'PLU_USER_TYPE' );
								if($adminUser){
									$userTypes = array(
											'admin' => 'PolarLink Admin',
											'normal' => 'Normal User'
									);
								} else {
									$userTypes = array(
											'csr' => 'Polar Beverage CSR',
											'admin' => 'PolarLink Admin',
											'normal' => 'Normal User'
									);
								}
								$ele->setValueOptions($userTypes);
								$ele->setValue($valUserType);
								$ele->setAttribute('onchange', 'return addActiveClass(1);');
								echo $this->formRow ( $ele );
								
								
								?>
							</fieldset>
							</div>
								</div>
								<div class="buttons">
				                <?php
				                echo $this->formRow ($form->get ( 'csr_user_field'));
				              
				                echo $this->formButton($form->get('save')->setLabel('Save User Details'));
				                echo $this->formButton($form->get('Cancel'));
				                ?>
				
				                </div>
			 					<?php
									echo $this->form()->closeTag();
								?>
								<div class="clearfix"></div>
							</div>
                        </div>
                        <div id="user-defaults" class="tab-pane">
                        <div class="clearfix"></div>
                        <div class="margin-top10 margin-bottom20"><em>The information below will be the default selection for placing orders as this user.<br />These settings will override any defaults defined for the Customer Group.</em></div>
                        <div class="clearfix"></div>
							<div class="ordering-option padding8 margin-top30 customer-defaults">
<!-- 								<h2 class="heading">Select Customer Defaults</h2> -->
								<div class="margin-top30">
											
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="clearfix"></div>
							<div class="modal modal-shipTo" id="myModalShipTo" role="dialog">
							<div class="modal-dialog">
							<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Select Default Ship-To</h4>
      </div>
      <div class="modal-body">
								
									<div class="padding8">
										<div class="search-box searchBoxForShipTo margin-top10">
											
												<?php $shippingSearchForm->setAttribute('action', $this->url('user/csrCustomerDetail', array('controller' => 'user', 'action' => 'csr-customer-detail', 'id' => $customerId)));
								$shippingSearchForm->setAttribute('id', 'customer-search-shipping-form');
								// $shippingSearchForm->setAttribute('class', 'col-md-12 form-signin login-form information-form margin-top0');
								
								$shippingSearchForm->setAttribute('onsubmit', 'return AjaxSearchShipTos()');								
								$shippingSearchForm->prepare();
								echo $this->form()->openTag($shippingSearchForm);
							
                     
                     			echo $this->formRow($shippingSearchForm->get('SEARCHPARAMETER')); 
                     			echo $this->formRow($shippingSearchForm->get('SUBMIT'));                     
                     			echo $this->formRow($shippingSearchForm->get('searchshipping'));
                     			echo $this->form()->closeTag();
                     			?>
											                  
										</div>
										<div class="clearfix"></div>
										<div class="table-responsive selected-table dataForShipTos margin-bottom0">
											<section class="table-section">
												<div class="table-scroll">
													<table class="table-striped ship-order">
														<thead>
															<tr>
																<th>Cust.#CuCuCu<div>Cust.#</div></th>
																<th>Shp# ShShS<div>Shp#</div></th>
																<th>Ship To Name <div>Ship To Name</div></th>
																<th>Address <div>Address</div></th>
																<th>City <div>City</div></th>
																<th>State Sta<div>State</div></th>
																<th>Zip <div>Zip</div></th>
															</tr>
														</thead>
														<tbody  id="popUpDataShippingForm">
															<?php  if(!empty($customerShipTos['output'])){ 
																$showButtonsDefaultShipTo = true;
	                            	foreach($customerShipTos['output'] as $shipTo){
										$class = '';
										if(!empty($trimmedDefaultShipTo) && !empty($trimmedDefaultCustNo)) { 
													if(($trimmedDefaultShipTo == trim($shipTo['ST_NUM'])) && ($trimmedDefaultCustNo == trim($shipTo['ST_CUST']))){
																	$class = ' active';
													}
										}
										
										$combinedId = trim($shipTo['ST_NUM']).'_'.trim($shipTo['ST_CUST']);
	                            	?>
	                            	<tr class="shipToDefaultSelectable<?php echo $class; ?>" id="<?php echo 'stnum_'.$combinedId; ?>">
	                                    <td id="<?php echo 'customerName_'.$combinedId; ?>"><?php echo $shipTo['ST_CUST']; ?></td>
	                                    <td><?php echo $shipTo['ST_NUM']; ?></td>
	                                    <td id="<?php echo 'name_'.$combinedId; ?>"><?php echo $shipTo['ST_NAME']; ?></td>
	                                    <td><?php
										$trimmedShipTo = trim($shipTo['ST_ADR2']);
	                                    echo $shipTo['ST_ADR1'].(!empty($trimmedShipTo)? ' - '.$trimmedShipTo:''); ?></td>
	                                    <td><?php echo $shipTo['ST_ADR3']; ?></td>
	                                    <td><?php echo $shipTo['ST_STATE']; ?></td>
	                                    <td><?php echo $shipTo['ST_ZIP']; ?><span id="<?php echo 'defaultShippingMethod_'.$combinedId; ?>" style="display: none;"><?php echo trim($shipTo['SHIP_METHOD']); ?></span></td>
	                                </tr>
	                            <?php 
	                            }
                            } else { 
									$showButtonsDefaultShipTo = false;
							?>
		                            <tr>
		                            	<td colspan="7">No Ship-To exists</td>
		                            </tr>
                            <?php } ?>
														</tbody>
													</table>
												</div>
											</section>
										</div>
										<?php if($showButtonsDefaultShipTo){ ?>
										<div class="margin-top20">
	                    <button onclick="return changeDefaultShipTo()" type="button" class="btn">Select Ship-To</button>
	                    <button onclick="$('#myModalShipTo').modal('toggle');" type="button" class="btn">Cancel Ship-To Selection</button>
	                    </div>
	                    <?php } ?>
									</div>
								</div>
								<div class="clearfix"></div>
								</div>
							</div>
							 </div>
                        </div>
					</div>
                </div>
               
             </div>
             <?php if($setDirtyFlag){ ?>
             <script type="text/javascript">
             changeDirtyFlag(true);
             </script>
             	
             <?php } ?>
             <script type="text/javascript">
             $(document).ready(function(){
            	 $('.shipToDefaultSelectable').click(
                    	  function() {
            					
            					$('.shipToDefaultSelectable').removeClass('active');
            					$(this).addClass('active');
            					
            				});
            	 $(".nav-tabs a[data-toggle=tab]").on("click", function(e) {
            		 if(_isDirty){
 				        e.preventDefault();
 				       if(confirm("There are unsaved changes on this page. Do you still want to continue?")){
 				    	  changeDirtyFlag(false);
 				    	 activeTab = $(this).attr('href');
 				    	LoadAjaxDataTabs(activeTab, '0');
						return true;
						
 				       } else{
 				    	  return false;
 				       }
            				
            				
            			} else {
            				activeTab = $(this).attr('href');
            				LoadAjaxDataTabs(activeTab, '0');
    							return true;					        		    
	            			}
            		 
            		              		});

            		var activeTab = $("ul#tabs li.active a").attr('href');
            		
            		// alert(activeTab);
                 });

             function changeDefaultShipTo(){
            	 var idShipTo = false;
            	 var combinedId = '';
            	 if($('.ship-order').find('.active').length > 0){
            		 idShipTo = $('.ship-order').find('.active').attr('id');
            	 }

            	 console.info('[jlopez] - %o', $('.ship-order').find('.active'));
            	 
            	 if(idShipTo == false){
					bootbox.alert('Please Select a Ship To Address');
					return false;
            	 }
            	 
 					idShipToArray = idShipTo.split('_');
 					combinedId = idShipToArray['1'] + '_' + idShipToArray['2'];
 					$('#CustomerDefaultAddressFull').html(
 		 					'<a onclick="removeDefaultUserShipTo()" title="Clear selected Ship-To" alt="Clear selected Ship-To" class="customer_default_close" href="javascript:void(0)"><i class="fa fa-times-circle">&nbsp;</i></a><div class="customer_default_text height_inherit">'
 		 					+ $('#name_' + combinedId).html() + '<br />'
							+ $('#address_' + combinedId).html() + '<br />'
							+ $('#city_' + combinedId).html() + ', '
							+ $('#state_' + combinedId).html() + ' - '
							+ $('#zip_' + combinedId).html()
							+ '</div>'
 		 			);
 					$('#plu_cust_number').val(idShipToArray['2']);
 					$('#plu_default_shipto').val(idShipToArray['1']);
 					$('#defaultShipToCustNoShipNo').html(idShipToArray['2'] + ' / ' + idShipToArray['1']).css({'margin-left': '30px'});

 					console.log('[jlopez] - updating shipping to...');
 					
 					$('#myModalShipTo').modal('toggle');
 					changeDirtyFlag(true);
					return false;

             }

             function removeDefaultUserShipTo(){
            	 bootbox.confirm('Are you sure, you want to clear the current ship To Address?', function( result){
      				if(result == true){
      					$('#CustomerDefaultAddressFull').html('');
     					$('#plu_cust_number').val('0');
     					$('#plu_default_shipto').val('0');
     					$('#defaultShipToCustNoShipNo').html('No Default Ship-To Selected').css({'margin-left': '0px'});
     					changeDirtyFlag(true);
      				
      				} else {
      						//return false;					
      					}

      				 });
             }

             function AjaxSearchShipTos(){
            	 var searchShippingText = $('#searchShippingText').val().trim();
            	 var customerId = $('#customerIdSearchShipping').val().trim();
            	 $('#loading-image').show();
            		// sending the ajax request
            	    $.ajax({
            	        url: '/user/ajax-search-ship-to',
            	        type: "POST",
            	        data:  {'search': searchShippingText, 'customerId' : customerId},
            	     //   dataType: "html",
            	        async: false,
            	        success: function(result) {
            	        	 $('#popUpDataShippingForm').html(result);
            	        	 return false;
            	            // do nothing here
            	     
            	        },
            	        failure: function(errMsg) {
            	            alert(errMsg);
            	            return false;
            	        },
            	        complete: function (){
            	        	$('#loading-image').hide();
            	        	return false;
            	        }
            	    });
            	    return false;
             }


             function LoadAjaxDataTabs(tabIndex, formPost){
                if(tabIndex == '' || tabIndex == undefined){
            		var activeTab =  $("ul#tabs li.active a").attr('href');
				} else {
					activeTab = tabIndex;
				}
            	 
            	 if(activeTab == '#user-details'){
					formId = 'user-edit-form';
            	 } else if(activeTab == '#user-defaults'){
					formId = 'user-defaults-form';
            	 }
            	 
            	 $('#loading-image').show();
            		// sending the ajax request
            		if(formPost == '1' && formId != ''){
                		
						var dataToSend = {'userId': '<?php echo $userId; ?>', 'activeTab': activeTab, 'formData': $('#'+formId).serialize()};
            		} else {
            			var dataToSend = {'userId': '<?php echo $userId; ?>', 'activeTab': activeTab};
            		}
            		
            	    $.ajax({
            	        url: '/user/csr-user-load-data',
            	        type: "POST",
            	        data:  dataToSend,
            	     //   dataType: "html",
            	        async: false,
            	        success: function(result) { // alert(result); return false;
                	        if(activeTab == '#user-details'){
									$('#user-details').html(result);
                	        }else if(activeTab == '#user-defaults'){
									$('#user-defaults').html(result);
                	        }
//                 	        else if(activeTab == '#users'){
// 									$('#users').html(result);
//                 	        }
            	        	 
            	        	 return false;
            	            // do nothing here
            	     
            	        },
            	        failure: function(errMsg) {
            	            alert(errMsg);
            	            return false;
            	        },
            	        complete: function (){
            	        	$('#loading-image').hide();
            	        	if(activeTab == '#user-details'){
            	        		addActiveClass(0);
            	        	}
            	        	return false;
            	        }
            	    }); 
            	    return false;
             }

             function changePasswordOpen(){
				//	$('.change-password-link').toggle();
					var valChangePwd = $('#csr_change_pwd').val();
					if(valChangePwd == '1')
						$('#csr_change_pwd').val('0');
					else
						$('#csr_change_pwd').val('1');
					$('.change-password-block').toggle();
             }
             addActiveClass(0);

             </script>
