<div class="col-md-12 col-sm-12 col-xs-12">
	<h1>An error has occurred while processing your order...</h1>
	<h5>If the error persists please contact support and try again later.</h5>
	<div class="ordering-option padding8">
		<div style="float:right"><h5><a href="/user">Go back to My Orders</a></h5></div>
		<br/>
    	<div class="colorred">
    			<h4><a>#</a> <?php print($error) ?></h4>
    	</div>
    </div>
</div>
