<?php if(!empty($flashMessages)){ ?>
<div class="alert alert-success fade in modal-content custom-success-content">
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<?php foreach($flashMessages as $flashMessage){ ?>
			    <?php echo $flashMessage; } ?>
		</div>	
		
<?php } ?>

<div class="col-md-12 col-sm-12 col-xs-12">
                <h1>Announcements</h1>
                <div class="table-responsive">
                	<section class="table-section">
  					<div id="polarlink-announcements-container" class="table-scroll">
                    <table id="polarlink-announcements" class="table-striped ship-order">
                        <thead>
                            <tr>
                                <th>Date<div>Date</div></th>
                                <th>Message<div>Message</div></th>
                            </tr>
                        </thead>
                        <tbody>
                           <?php if(!empty($currentAnnouncement['message'])){ ?>
                           <tr>
                           		<td colspan="2"><?php echo $currentAnnouncement['message']; ?></td>
                           </tr>
                           <?php } else if (empty($currentAnnouncement['output'])){ ?>
                           <tr>
                           		<td colspan="2">No current announcements.</td>
                           </tr>
                           <?php } else { 
                           		foreach($currentAnnouncement['output'] as $announcement){
                           	?>
                           <tr>
	                           <td><?php 
	                           $unixtime = strtotime($announcement['PLA_END_DATE']);
	                           echo $this->dateFormat(
								    $unixtime,
								    IntlDateFormatter::FULL, // date
								    IntlDateFormatter::NONE, // time
								    "en_US"
								);  ?></td>
	                           <td><?php echo $announcement['PLA_MESSAGE']; ?></td>
                           </tr>
                           <?php
                           		} 
							} ?>
                        </tbody>
                    </table>
                	</div>
                	</section>
                </div>
                <div class="ordering-option">
                	<h2 class="heading">Ordering Options</h2>
                	<br/>
                	<?php 
                    	/**
                    	 * Display menu to resume an order (if any)
                    	 */
                    	echo $this->partial('partials/dashboard/options.phtml',
                    	
                    	    [
                    	        'identity' => $identity,
                    	
                    	        'partialEditCurrentOrder' => $partialEditCurrentOrder
                    	
                    	    ]
                    	);
                        	   
                       
                       echo $this->partial(
                        	       
                        'partials/dashboard/pending/orders.phtml', 
                        	       
                            [
                        	       
                        	   'identity' => $identity,
                        	       
                        	   'pendingOrders' => $pendingOrders
                                
                        	 ]
                        ); ?>
                        	    
                        </div>
             </div>
             <script type="text/javascript">
             /*
             var windowHeight = $(window).height();
             var headerHeight = $('.header-group').height();
             var footerHeight = $('.ordering-option').height();
             var tableResponsiveHeight = $('.table-scroll').height();
             var remainingHeight = windowHeight - headerHeight - footerHeight - 230;
              
             if(tableResponsiveHeight > remainingHeight && windowHeight > remainingHeight){
            	
				$('.table-scroll').css('max-height', remainingHeight);
             }
             */
             </script>