<?php
use Zend\Session\Container;

$params = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
?>
 <div class="row inner-page-top-address margin-top-order">
	 <?php  echo $this->partial('/partials/order-header-info.phtml', array('getOrderHeader' => $getOrderHeader)); ?>
</div>
			<div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12 steps-complete">
            	<em>Steps to complete your order:</em>
            </div> </div>
            <div class="row">
                <ul class="order-tabs">
                    <?php
                    
                    $breadcrumbParams = array();
                     
                    $breadcrumbParams['resource'] = 'review.phtml';
                     
                    $breadcrumbParams['orderingStep'] =
                        (int)$getOrderHeader['output']['PLINK_ENTRY_STEP'];
                     
                    $breadcrumbParams['excludeSubstitutes'] =
                        !(trim($getOrderHeader['output']['SUBS_REQUIRED']) === 'Y');
                     
                    echo $this->partial('partials/breadcrumbs/breadcrumbs.phtml',$breadcrumbParams);
                    
                    $showSubstitutesTab = !$breadcrumbParams['excludeSubstitutes'];

                     ?>
                </ul>
            </div>
             <div class="col-md-12 col-sm-12 col-xs-12">
             	<h1 class="margin-bottom25">Order Summary / Review</h1>
				<ul class="review-text-list">
					<li>Select a tab, below, to review your order.<!--   Correct any errors (indiciated by red) before clicking the submit button, below. --></li>
					<li>To continue adding items, click the "Continue Ordering" button.</li>
					<li>If you click "Cancel". You will have an option to save this order for later.</li>
				</ul>

                <div class="item-search-tabs margin-top20">
                    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                        <li class="<?php echo ($params['tab']=='') ? 'active' : ''; ?>"><a href="#Summary" data-toggle="tab">Summary</a></li>
                        <li class="<?php echo ($params['tab']=='Shipping') ? 'active' : ''; ?>"><a href="#Shipping" data-toggle="tab">Shipping</a></li>
                        <li class="<?php echo ($params['tab']=='Items') ? 'active' : ''; ?>"><a href="#Items" data-toggle="tab">Items</a></li>
                        <?php if($showSubstitutesTab){ ?><li class="<?php echo ($params['tab']=='Substitutes') ? 'active' : ''; ?>"><a href="#Substitutes" data-toggle="tab">
                        Substitutes
<!--                         <span>Substitutes<sup>**</sup></span> -->
                        </a></li>
 						<?php } ?>
                        <li class="<?php echo ($params['tab']=='Attachments') ? 'active' : ''; ?>"><a href="#Attachments" data-toggle="tab">Attachments</a></li>

                       
                    </ul>
                    <div id="my-tab-content" class="tab-content">
                        <div id="Summary" class="tab-pane <?php echo ($params['tab']=='') ? 'active' : ''; ?>">
                            <div class="ordering-option padding8 ">
							<h2 class="heading">Current Order Totals</h2>
							<div class="total-amount tab-order-total margin-top35">
								<ul class="border-color">
									<div class="total-heading">Product Amount<div class="clearfix"></div><span class="total-desc">(excluding deposits)</span></div>
									<li class="flright">$<?php echo number_format(trim($getOrderTotals['amount']), '2', '.', ','); ?></li>
								</ul>
								<ul class="border-color">
									<div class="total-heading align-center">Quantities<!-- <div class="clearfix"></div><span class="total-desc">&nbsp;</span> --></div>
									<li><span>Cases:</span> <?php echo number_format(trim($getOrderTotals['caseQty']), '0', '.', ','); ?></li>
									<li><span>Pallets:</span> <?php echo number_format(trim($getOrderTotals['palletQty']), '2', '.', ','); ?></li>
								</ul>
								<ul class="border-color">
									<div class="total-heading align-center">Weights<div class="clearfix"></div><span class="total-desc">&nbsp;</span></div>
									<li><span>Products:</span> <?php echo  number_format(trim( $getOrderTotals['prodWeight']), '0', '.', ','); ?> lbs</li>
									<li><span>Pallets:</span> <?php echo number_format(trim($getOrderTotals['palletWeight']), '0', '.', ','); ?> lbs</li>
									<li><span>Total:</span> <?php echo number_format(trim($getOrderTotals['totalWeight']), '0', '.', ','); ?> lbs</li>
								</ul>
								<div class="clearfix"></div>
								<div class="col-sm-12 col-md-6">
                                    <p class="table-notes fontOrange margin-top20 margin-bottom0">
                                       Total Order Amount is subject to price verification
                                    </p>
                            	</div>
                                   <?php if($getOrderTotals['prodWeight'] > 46000){ ?>
                                       <div class="col-sm-12 col-md-6">
                                           <div class="weight-warning margin-top10 text-left">
                                               Warning! Total weight exceeds 46,000 lbs!
                                           </div>
                                        </div>
                                <?php } ?>
								
							</div>
							<div class="clearfix"></div>
						</div>
                        </div>
                        <div id="Shipping" class="tab-pane <?php echo ($params['tab']=='Shipping') ? 'active' : ''; ?>">
                        	<div class="ordering-option padding8 shipping-box1">
								<h2 class="heading">Shipping Information</h2>
								<div class="col-md-10 form-signin login-form information-form margin-bottom20 text-center-responsive">
									<fieldset class="col-md-12 shipping-info">
										<label for="inputEmail">Cust# / Ship To:</label>
										<span class="normal-text"><?php echo (!empty(trim($getOrderHeader['output']['OH_CUSTNO']))?trim($getOrderHeader['output']['OH_CUSTNO']):'-').' / '.(!empty(trim($getOrderHeader['output']['OH_SHP2_NUM']))?trim($getOrderHeader['output']['OH_SHP2_NUM']):'-'); ?></span>
									</fieldset>
									<fieldset class="col-md-12 shipping-info">
										<label for="inputEmail">Shipping Address:</label>
										<span class="normal-textarea">
										<?php echo (!empty(trim($getOrderHeader['output']['OH_SHP2_NAME']))?trim($getOrderHeader['output']['OH_SHP2_NAME']).'<br />':''); ?>
                            <?php echo (!empty(trim($getOrderHeader['output']['OH_SHP2_ATTN']))?'Attn: '.trim($getOrderHeader['output']['OH_SHP2_ATTN']).'<br />':''); ?>
                            <?php echo (!empty(trim($getOrderHeader['output']['OH_SHP2_ADDR1']))?trim($getOrderHeader['output']['OH_SHP2_ADDR1']).'<br />':''); ?>
                            <?php echo (!empty(trim($getOrderHeader['output']['OH_SHP2_ADDR2']))?trim($getOrderHeader['output']['OH_SHP2_ADDR2']).'<br />':''); ?>
                            <?php echo (!empty(trim($getOrderHeader['output']['OH_SHP2_ADDR3']))?trim($getOrderHeader['output']['OH_SHP2_ADDR3']).', ':'').(!empty(trim($getOrderHeader['output']['OH_SHP2_STATE']))?trim($getOrderHeader['output']['OH_SHP2_STATE']).' ':'').(!empty(trim($getOrderHeader['output']['OH_SHP2_ZIP']))?trim($getOrderHeader['output']['OH_SHP2_ZIP']).' ':''); ?></span>
									</fieldset>
									<fieldset class="col-md-12 shipping-info">
										<label for="inputEmail">Shipping Method:</label>
										<span class="normal-text"><?php echo (!empty(trim($getOrderHeader['output']['OH_SHIP_METHOD_TEXT']))?trim($getOrderHeader['output']['OH_SHIP_METHOD_TEXT']):''); ?></span>
									</fieldset>
									<div class="info-button info-review-shipping">
								<button type="button" class="btn" onclick="location.href = '<?php echo $this->url('user/orderShipping').'?redirect=order-shipping'; ?>';">Edit...</button>
							</div>
								</div>
								<div class="clearfix"></div>
							</div>

                <?php
																$form->setAttribute ( 'action', $this->url ( null, array (
																		'controller' => 'user',
																		'action' => 'order-header'
																) ) );
																$form->setAttribute ( 'id', 'order-review-header-form' );
																$form->setAttribute ( 'class', 'col-md-12 form-signin login-form information-form margin-top20' );

																$form->prepare ();
																echo $this->form ()->openTag ( $form );
																?>
							<div class="ordering-option padding8 margin-top60">
                	<h2 class="heading">Additional Order Information</h2>
<!--                     <form class="col-md-10 form-signin login-form information-form"> -->
                	<div class="margin-top60 text-center-responsive">
                    	<fieldset class="col-md-12 shipping-info">
                            <label for="inputEmail">Primary PO#:</label>
                             <?php
								$valOhPo1 = $form->getInputFilter ()->getValue ( 'OH_PO1' ); // die;
								if (empty ( $valOhPo1 )) {
									$valOhPo1 = (! empty ( trim ( $getOrderHeader ['output'] ['OH_PO1'] ) ) ? trim ( $getOrderHeader ['output'] ['OH_PO1'] ) : '');
								}
								//$ele = $form->get ( 'OH_PO1' );
								//$ele->setValue($valOhPo1)->setAttribute('readonly', 'readonly');
								//echo $this->formRow ( $ele );

								?>
								<span class="normal-text"> <?php echo $valOhPo1; ?> </span>

<!--                             <input type="text" autofocus="" required="" placeholder="" class="form-control pull-left" id="inputEmail" /> -->
                        </fieldset>
                        <fieldset class="col-md-12 shipping-info">
                            <label for="inputPassword">Alternate PO# 1:</label>
                            <?php
                            	$valOhPo2 = $form->getInputFilter ()->getValue ( 'OH_PO2' ); // die;
                            				if (empty ( $valOhPo2 )) {
																													$valOhPo2 = (! empty ( trim ( $getOrderHeader ['output'] ['OH_PO2'] ) ) ? trim ( $getOrderHeader ['output'] ['OH_PO2'] ) : '');
																												}
																											//	echo $this->formRow ( $form->get ( 'OH_PO2' )->setValue ( $valOhPo2 )->setAttribute('readonly', 'readonly') );

																												?>
																												<span class="normal-text"> <?php echo $valOhPo2; ?> </span>
<!--                             <input type="text" required="" placeholder="" class="form-control pull-left" id="inputText" /> -->
                        </fieldset>
                        <fieldset class="col-md-12 shipping-info">
                            <label for="inputPassword">Alternate PO# 2:</label>
                             <?php

																												$valOhPo3 = $form->getInputFilter ()->getValue ( 'OH_PO3' ); // die;
																												if (empty ( $valOhPo3 )) {
																													$valOhPo3 = (! empty ( trim ( $getOrderHeader ['output'] ['OH_PO3'] ) ) ? trim ( $getOrderHeader ['output'] ['OH_PO3'] ) : '');
																												}
																												// echo $this->formRow ( $form->get ( 'OH_PO3' )->setValue ( $valOhPo3 )->setAttribute('readonly', 'readonly') );

																												?>
																												<span class="normal-text"> <?php echo $valOhPo3; ?> </span>
<!--                             <input type="text" required="" placeholder="" class="form-control pull-left" id="inputText" /> -->
                        </fieldset>
                        <fieldset class="col-md-12 shipping-info">
                            <label for="inputPassword"><?php if(trim($getOrderHeader['output']['OH_SHIP_METHOD_CODE']) != 'P'){ echo 'Delivery'; } else { echo 'Pickup'; } ?> Date:</label>
                             <?php
                            $delivDateVal = $form->getInputFilter ()->getValue ( 'OH_REQ_DELIV_DATE' ); // die;
                            if (empty ( $delivDateVal )) {
                            	$delivDateVal = (! empty ( trim ( $getOrderHeader ['output'] ['OH_REQ_DELIV_DATE'] ) ) ? trim ( $getOrderHeader ['output'] ['OH_REQ_DELIV_DATE'] ) : '');
                            	if(!empty($delivDateVal)){
										 $delivDateTotalDigits = strlen($delivDateVal);
										if($delivDateTotalDigits == '8'){
													$delivDateYear = substr($delivDateVal, '0', '4');
													$delivDateMonth = substr($delivDateVal, '4', '2');
													$delivDateDay = substr($delivDateVal, '6', '2');
													$delivDateVal = $delivDateMonth.'/'.$delivDateDay.'/'.$delivDateYear;
										} else {
													$delivDateVal = '';
										}
								}
                            }

                            //echo $this->formRow($form->get('OH_REQ_DELIV_DATE')->setValue ( $delivDateVal )->setAttribute('readonly', 'readonly'));

                            ?>
                            <span class="normal-text"> <?php echo $delivDateVal; ?> </span>
<!--                             <input type="text" required="" placeholder="" class="form-control pull-left" id="inputText" /> -->
                            <!--<span class="icons"><a href=""><img src="img/calendar_icon.png" alt="" /></a></span>-->
                        </fieldset>
                        <?php if(trim($getOrderHeader['output']['OH_SHIP_METHOD_CODE']) != 'P'){ ?>
                        <fieldset class="col-md-12 shipping-info">
                            <label for="inputPassword">Delivery Time:</label>

                            <?php
                            $delivTimeVal = $form->getInputFilter ()->getValue ( 'OH_REQ_DELIV_TIME' ); // die;
                            if (empty ( $delivTimeVal )) {
                            	$delivTimeVal = (! empty ( trim ( $getOrderHeader ['output'] ['OH_REQ_DELIV_TIME'] ) ) ? trim ( $getOrderHeader ['output'] ['OH_REQ_DELIV_TIME'] ) : '');
                            	if(!empty($delivTimeVal)){
                            		$delivTimeTotalDigits = strlen($delivTimeVal);
                            		if($delivTimeTotalDigits == '5'){
												$delivTimeHour = substr($delivTimeVal, '0', '1');
												$delivTimeMinutes = substr($delivTimeVal, '1', '2');
												$delivTimeAmPm = '';
												if($delivTimeHour > 12){
														$delivTimeHour = $delivTimeHour-12;
													$delivTimeAmPm = 'pm';
												} else {
													if($delivTimeHour < 10){

													}
													$delivTimeAmPm = 'am';
												}
												$delivTimeVal = $delivTimeHour.':'.$delivTimeMinutes.$delivTimeAmPm;

									} else if($delivTimeTotalDigits == '6'){
                            			$delivTimeHour = substr($delivTimeVal, '0', '2');
                            			$delivTimeMinutes = substr($delivTimeVal, '2', '2');
                            			$delivTimeAmPm = '';
                            			if($delivTimeHour > 12){
														$delivTimeAmPm = 'pm';
														$delivTimeHour = $delivTimeHour-12;
										} else {
												if($delivTimeHour < 10){

												}
														$delivTimeAmPm = 'am';
										}
                            			$delivTimeVal = $delivTimeHour.':'.$delivTimeMinutes.$delivTimeAmPm;
                            		} else {
                            			$delivTimeVal = '';
                            		}
                            	}
                            }

                          //  echo $this->formRow($form->get('OH_REQ_DELIV_TIME')->setValue( $delivTimeVal ));
                            ?>

                            <span class="normal-text"> <?php echo $delivTimeVal; ?> </span>
                        </fieldset>
                        <?php } ?>
                        <fieldset class="col-md-12 shipping-info">
                            <label for="inputPassword">Notes / Comments:</label>
                            <?php

			$notesVal = $form->getInputFilter ()->getValue ( 'OH_NOTES' ); // die;
			if (empty ( $notesVal )) {
				$notesVal = (! empty ( trim ( $getOrderNotes ['notes'] ) ) ? trim ( $getOrderNotes ['notes'] ) : '');
			}
                          //  echo $this->formRow($form->get('OH_NOTES')->setValue ( $notesVal )->setAttribute('readonly', 'readonly'));

                           // echo $this->formCollection($form->get('categories'));

                            ?>
                            <span class="normal-text"> <?php echo $notesVal; ?> </span>
                        </fieldset>
                          <div class="clearfix"></div>
                        <div class=" info-button info-review-shipping padding-bottom">
								<button class="btn" type="button" onclick="location.href = '<?php echo $this->url('user/orderHeader').'?redirect=review-order'; ?>'">Edit...</button>
							</div>
                    </div>
                    <div class="clearfix"></div>
                </div>

							 <?php	echo $this->form ()->closeTag ();		?>
							<div class="clearfix"></div>
                        </div>
                        <div id="Items" class="tab-pane <?php echo ($params['tab']=='Items') ? 'active' : ''; ?>">
                        	<div class="order-heading margin-top20">Current items in this order
                        	<span class="info-button flright">
								<button class="btn" type="button" onclick="location.href = '<?php echo $this->url('user/itemSearch').'?redirect=review-order'; ?>'">Edit...</button>
							</span></div>
							<div class="clearfix"></div>
							<div class="table-responsive">
								<table class="table table-striped ship-order margin-bottom8">
									<thead>
										<tr>
											<th>Product</th>
											<th>Description</th>
											<th>Qty</th>
<!-- 											<th>RMV</th> -->
											<th>UOM</th>
											<th>Price</th>
											<th>Ext. Price</th>
											<th>Pallets</th>
											<th>Cases</th>
											<th>Units</th>
										</tr>
									</thead>
									<tbody>
									<?php if(!empty($getOrderLineItems['output'])){
                            	foreach($getOrderLineItems['output'] as $orderLine){
									$itemNumber = trim($orderLine['OL_ITEM_NUM']);
							?>
									<tr class="<?php echo $itemNumber; ?>">
                                    <td><?php echo $itemNumber; ?></td>
                                    <td desc='desc'><?php echo $orderLine['OL_ITEM_DESC']; ?></td>
                                    <td class="text-right"><?php echo number_format($orderLine['OL_QTY_ORD'], '0'); ?></td>
                                    <!-- <td style="text-align: center;"><a href="javascript:void(0)" onclick="removeItemFromOrder(<?php echo $itemNumber; ?>)"><img width="16px" src="<?php echo $this->basepath('/img/close.png'); ?>" alt="RMV" /></a></td>  -->
                                    <td uom='uom'><?php echo trim($orderLine['OL_SELL_UOM']); ?></td>
                                    <td class="text-right"><?php echo number_format($orderLine['OL_NET_PRICE'],  2, '.', ','); ?></td>
                                    <td class="text-right" copy_from="ext_price"><?php echo number_format($orderLine['OL_EXT_PRICE'],  2, '.', ','); ?></td>
                                    <td class="text-right" copy_from="pallet_qty"><?php
                                    $trimPalletQty = trim(number_format($orderLine['ITM_PALLET_QTY_ORD'], '2'));
                                     if($trimPalletQty < 1){
										echo substr($trimPalletQty, '1', strlen($trimPalletQty));
									} else {
										echo $trimPalletQty;
									}
                                    ?></td>
                                    <td class="text-right" copy_from="case_qty"><?php echo number_format($orderLine['ITM_CASE_QTY_ORD'], 0); // $orderLine['ITM_CASE_QTY_ORD']; ?></td>
                                    <td class="text-right" copy_from="unit_qty"><?php echo number_format($orderLine['ITM_UNIT_QTY_ORD'], 0); ?></td>
                                </tr>
								<?php }
                            } else { ?>
                            <tr>
                            <td colspan="10">No Products in the current order</td>
                            </tr>
                            <?php } ?>
									</tbody>
								</table>
							</div>
                    		<div class="clearfix"></div>
                        </div>
                        <?php if($showSubstitutesTab){ ?>
                        <div id="Substitutes" class="tab-pane <?php echo ($params['tab']=='Substitutes') ? 'active' : ''; ?>">
							<div class="order-heading margin-top10">Substitute Items on this Order
							<span class="info-button flright">
								<button class="btn" type="button" onclick="location.href = '<?php echo $this->url('user/substitutes').'?redirect=subtitutes'; ?>'">Edit...</button>
							</span>
							</div>
							<div class="clearfix"></div>
                        	<div class="margin-top5">
								<em>Below are your current selections for substitute items.<br>
<!-- 								To change priority, hold the "Move" icon and slide the items up or down.<br> -->
								Click the change button to add or remove substitutes.
								</em>
							</div>
							<div class="clearfix"></div>
							 <?php
                    echo $this->partial('/partials/substitutes-list.phtml', array(
                    		'getListSubstitutes' => $getListSubstitutes,
							'configSubstitutes' => $configSubstitutes,
							'removeHide' => true
                    ));
                    ?>
<!-- 							<p class="table-notes">You have only selected 2 substitute items. You must select at least 3, and no more than 6, substitutes.</p> -->
							<!--  <div class="click-items">Please <a href="<?php echo $this->url('user/substitutes'); ?>"><em>click here to select substitute items.</em></a></div> -->
							<div class="clearfix"></div>
                        </div>
                    	<?php } ?>
						 <div id="Attachments" class="tab-pane <?php echo ($params['tab']=='Attachments') ? 'active' : ''; ?>">
						    <div class="table-responsive">
						        <div class="order-heading margin-top20"> File Attachments for this order
						            <span class="info-button flright">
						              <a href="<?php echo $this->url('user/OrderAttachment', array('controller' => 'user', 'action' => 'order-attachment'))?>" class="btn" > Attach a file </a>
						            <!--  <a href="#" class="btn" > Attach a file </a>  -->
						            </span>
						        </div>
						       <div class="download-file"> Click on a file name to download the file.</div>
						       
						         <div class="table-responsive selected-table dataForShipTos download-table">
                    	<section class="table-section table-section-tow table-section-two">
  							<div class="table-scroll">
						        <table class="table-striped ship-order order-table-titles">
						            <thead>
						                <tr>
						                    <th width ="5%">&nbsp; </th>
						                    <th width="9%">Type <div>Type</div> </th>
						                    <th  width="43%">File Name <div>File Name</div></th>
						                    <th width="11%">Size <br> (bytes) <div class="table-titles">Size <br>(bytes)</div> </th>
						                    <th width="11%">Date <br> Added <div >Date <br> Added</div> </th>
						                    <th width="11%">Uploaded <br>By <div >Uploaded <br> By</div> </th>
						                    <th width="10%" >Delete <div class="table-titles-last">Delete</div> </th>
						                </tr>
						            </thead>
						            <tbody>

						            <?php if(!empty($dataOrderAttachment)) { ?>

						            <?php foreach($dataOrderAttachment as $order_attachement){?>
						                <tr >
						                    <td>
						                      <?php /* <a href="<?php echo $this->url('user/orderAttachmentFileDownload').'?fileName='. $order_attachement['PLAT_IFS_FILENAME'].'&fileNameOri='.$order_attachement['PLAT_UPL_FILENAME'].'&orderNumber='.$order_attachement['PLAT_ORDER_NO'];?>" title="Download File"><i aria-hidden="true" class="fa fa-download icons"></i> </a> */?>
						                        <?php /*  <a href="<?php echo $this->url('user/updateOrderAttachmentDescrption', array('controller' => 'user', 'action' => 'update-order-attachment-description','id'=> $order_attachement['PLAT_ATTACH_NO']))?>" > <i aria-hidden="true" class="fa fa-info-circle icons"></i> </a> */ ?>

						                  <a title="Edit Description" data-target="#myModal" data-toggle="modal"  data-orderno="<?php echo $order_attachement['PLAT_ORDER_NO']; ?>"  data-filename="<?php echo $order_attachement['PLAT_UPL_FILENAME']; ?>"  data-filesize="<?php echo number_format($order_attachement['PLAT_FILE_SIZE']); ?>"   data-platid ="<?php echo $order_attachement['PLAT_ATTACH_NO']; ?>" data-description="<?php echo base64_encode($order_attachement['PLAT_DESCRIPTION']); ?>" class="view-brn" href="#"><i class="fa fa-pencil-square-o icons_edit" aria-hidden="true"></i></a>
						                    </td>
						                    <td ><?php echo $order_attachement['PLAT_FILE_EXT']; ?></td>
						                    <td>
						                  	  <a href="<?php echo $this->url('user/orderAttachmentFileDownload').'?fileName='. $order_attachement['PLAT_IFS_FILENAME'].'&fileNameOri='.$order_attachement['PLAT_UPL_FILENAME'].'&orderNumber='.$order_attachement['PLAT_ORDER_NO'];?>" id='tool-tipfile<?php echo $order_attachement['PLAT_ATTACH_NO']; ?>' data-id='<?php echo $order_attachement['PLAT_ATTACH_NO']; ?>' class="download-files-word" role="button" date-html=true data-placement="right"  data-toggle="popover" data-trigger="focus" title="File Comments: " data-content="<?php echo $order_attachement['PLAT_DESCRIPTION']; ?><p>Click on file name to download file</p>"><?php echo $order_attachement['PLAT_UPL_FILENAME']; ?> </a> </td>
						                   	 <td align="right"><?php echo number_format($order_attachement['PLAT_FILE_SIZE']); ?></td>
						                    <td>
						                 	 	 <?php
						                   		 $date= explode('-',$order_attachement['PLAT_CRT_TIME']);
												 $monthName = date("M", mktime(0, 0, 0, $date['1'], 10));
						                   		 echo $monthName.' '.$date['2'].','.$date['0'];
						                  		 ?>
						                    </td>
						                    <td ><?php echo $order_attachement['PLAT_CRT_USER']; ?></td>
						                    <td align="center">
						                    <?php /* <a href="<?php echo $this->url('user/OrderAttachment', array('controller' => 'user', 'action' => 'order-attachment','id'=> $order_attachement['PLAT_ATTACH_NO']))?>" > <i class="fa fa-times-circle icons"></i> </a> 	*/ ?>
						                   <?php if(!empty($order_attachement['PLAT_ATTACH_NO'])){ ?><a href="javascript:void(0)" onclick="return removeItemOrderAttachment('<?php echo $order_attachement['PLAT_ATTACH_NO']; ?>','<?php echo $order_attachement['PLAT_ORDER_NO']; ?>','<?php echo $order_attachement['PLAT_UPL_FILENAME']; ?>',this);"> <i class="fa fa-times-circle icons delete-icon-align"></i></a><?php } ?>
						                    </td>
						                </tr>
						               

						                <?php } } else { ?>
					                            <tr>
					                           		 <td colspan="7">No Order attachment found!</td>
					                            </tr><?php }?>
					                             <tr>
						                <td id="dynamic_change_heigt" height="70px" colspan="7" ></td>
						                </tr>
						            </tbody>
						        </table>
						        </div></section></div>


		</div>
			<div class="clearfix"></div>
 		</div>
 	</div>
  </div>
                <?php
                if(($identity['PLU_POLAR_CSR'] != 'Y'))
                {
                $formOrderSubmit->setAttribute ( 'action', $this->url('user/reviewOrder', array('controller' => 'user', 'action' => 'review-order')));
                $formOrderSubmit->setAttribute ( 'id', 'submitOrder' );
                $formOrderSubmit->prepare ();
                echo $this->form ()->openTag ( $formOrderSubmit );
                ?>
                
                <div id="myModalAddNotificationList" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!-- Modal content-->
			    <div class="modal-content text-center">
			         <div class="alert alert-danger margin-top10" id="error_div" style="display:none;"></div>
			         <div class="margin-top20"> <em> You can enter one or more email addresses to receive a copy of the order details:</em></div>
                		  
							<fieldset class="row col-xs-10 col-xs-offset-1">
							
								<span class="" style="height:inherit;">
									<textarea id="csr_email_address" name="csr_email_address" style="width:100% !important;" class="form-control pull-left"></textarea>
								</span>
								
							</fieldset>
							<div class="clearfix"></div>
							<ul>
								  <li>You can enter multiple email addresses (max 2500 characters).</li>
								  <li>Separate each email address by comma.</li>
								  
								</ul>
								<div class="modal-footer">
								<button id="cancel-submit-order" type="button" class="btn btn-default" data-dismiss="modal">Cancel Submit</button>
								<button id="do-submit-order" type="button" class="btn btn-default pull-left" onclick="validateNotificationEmailGroup();">Submit Your Order</button>
			    </div>
			  </div>
			</div>
			</div>
                
                <div class="buttons review-buttons">
                <?php if($showMessage == '0'): ?>
                	<button type="button" onclick="$('#myModalAddNotificationList').modal();" class="btn" name="save">Submit Your Order</button>
                <?php else: ?>
                	<button type="button" class="btn" name="save" disabled>Submit Your Order</button>
                <?php endif; ?>
                <button class="btn" type="button" onclick="location.href = '<?php echo $this->url('user/itemSearch'); ?>';">Continue Ordering</button>
				<button class="btn" type="button" data-keyboard="true" onclick="return checkCancel('review');">Cancel Order</button>
                </div>
               <?php  if($showMessage == '1'){ ?>
                <p class="table-notes leadTimecalErrorMsg">
					
					<?php echo 'Delivery or Pickup date '.date("m/d/Y",strtotime($getOrderHeader ['output'] ['OH_REQ_DELIV_DATE'])).' is not valid because lead time date, '.date("m/d/Y",strtotime($reqLeadDate)).', is before today.You must change the delivery/pickup date on the <u class="reqDate-error"><a href="'.$this->url('user/orderHeader').'?redirect=review-order">order header page</a></u> before submitting this order';?>
					
					</p> <?php } ?>
                <div class="clearfix"></div>
                <div class="bottom-address Margin-top50px;">
                	
                	<?php 
                	
                	
                		
                		    $pluEmailValue = trim($identity['PLU_EMAIL_ADDRESS']);
                		    $elementEmail = $formOrderSubmit->get('PLU_EMAIL');
                		    if($request->isPost()){
                		        $pluEmailValue = $elementEmail->getValue();
                		    }
                		?>
                    		<em>An email confirmation will be sent to the following email address:</em>
                        	<div class="row margin-top10">
                        		<div class="col-md-4 col-sm-4 col-xs-12">
                        		<?php echo $this->formrow( $elementEmail->setValue($pluEmailValue) ); ?>
                        		</div>
                        		<div class="col-md-8 col-sm-8 col-xs-12 checkbox-text">
                        		<?php echo $this->formrow( $formOrderSubmit->get('PLU_EMAIL_SAVE') ); ?>
                        		 &nbsp;Save this as my permanent email address for order confirmation
                        		</div>
                        	</div>
                </div>
                <?php echo $this->form ()->closeTag(); ?>
                <?php } else { ?>
                
                                		<?php 
                      		$order_session = new Container('order');
                                		
                		    if(!empty(trim($customerEmails['output']['PLC_EMAILS']))
               		        || !empty(trim($order_session->offsetGet('mailto'))) ):
                		        $plcEmailsArray = explode(',', $customerEmails['output']['PLC_EMAILS']);
            		            print '<div class="margin-top20"> <em> Confirmation email will also be sent to these company email addresses:</em></div>';
            		            print '<br/>';
    		                    // print '<ul class="email-address-text">';
                            	
    		                    foreach($plcEmailsArray as $plcEmail):
                            	   print '<div class="margin-top"><em> '.trim($plcEmail).'</em></div>';
                            	endforeach;
                        	   
                            	// print '</ul>';
                		      endif;
                		      
                		      
                		      if($order_session->offsetExists('order_num')):
                		      
                		          if(!empty(trim($order_session->offsetGet('mailto')))):
                		      
                    		          $mailTo = implode(',', array_map(function($mail){
                    		              
                    		              return $mail.'<span class="review-order-customer-ship-to-email">(Customer Ship-To Email)</span>';
                    		              
                    		          }, explode(',', $order_session->offsetGet('mailto'))));
                    		          
                    		      
                    		          $mailTo = str_replace(',', '<br/>', $mailTo);
                    		          print '<div class="margin-top"><em> '.$mailTo.' </em></div>';
                    		      endif;
                		      
                		      
                		      endif;
                		      
                		      
                		 ?>
                		 
                <div class="buttons review-buttons">
                <?php if($showMessage == '0'){ ?>
                <button value="submit"  class="btn" name="save" type="button" data-toggle="modal" data-target="#myModalCSR">Submit Your Order</button>
                <?php } else { ?>
                <button value="submit"  class="btn" name="save" type="submit" disabled>Submit Your Order</button>
                <?php }?>
                
                    <button class="btn" type="button" onclick="location.href = '<?php echo $this->url('user/itemSearch'); ?>';">Continue Ordering</button>
					<button class="btn" type="button" data-keyboard="true" onclick="return checkCancel('review');">Cancel Order</button>
                </div>
                
                <?php  if($showMessage == '1'){ ?>
                <p class="table-notes leadTimecalErrorMsg">
					
					<?php echo 'Delivery or Pickup date '.date("m/d/Y",strtotime($getOrderHeader ['output'] ['OH_REQ_DELIV_DATE'])).' is not valid because lead time date, '.date("m/d/Y",strtotime($reqLeadDate)).', is before today.You must change the delivery/pickup date on the <u class="reqDate-error"><a href="'.$this->url('user/orderHeader').'?redirect=review-order">order header page</a></u> before submitting this order';?>
					
					</p> <?php } ?>
                <div class="clearfix"></div>
                
                <?php } ?>
                
				<div class="buttons-text">
				</div>
             </div>

             <script type="text/javascript">


				function checkValuesSubmitOrder(){
					
					var plu_email_save = $('input[name="PLU_EMAIL_SAVE"]:checked').length;
					var plu_email = $('input[name="PLU_EMAIL"]').val().trim();
					if(plu_email_save == '0' && plu_email == ''){
						if(confirm('Are you sure you do not want to receive an email confirmation for your order?')){
							sessionStorage.removeItem('emailRem');
							return true;
						} else {
							return false;
						}
					} else {
						sessionStorage.removeItem('emailRem');
						return true;
					}
				}

				function validateNotificationEmailGroup(){

					var dirtyEmailList  = $('#csr_email_address').val();
					var emailList = $.trim(dirtyEmailList);

					$('#error_div').html(null).hide();
					$('#do-submit-order').attr('disabled', 'disabled');

					$.post('/user/check-csr-review-order',
							 
							{ csr_email_address: emailList},

							function(data){

								if(!data.valid){

									$('#error_div').html(data.Message).show();
									$('#do-submit-order').removeAttr('disabled');

									return data.valid;
								}

								$('#submitOrder').submit();
							});

				}

			    function checkValuesSubmitOrderCSR(){
					
					
					var csr_email_save = $('#myModalCSR #csr_email_address').val().trim();
					$('#myModalCSR #error_div').html('').hide();
				
					 $.ajax({
							url: '/user/check-csr-review-order',
					        type: "POST",
					        data: {'csr_email_address':csr_email_save},
					        dataType: "json",
					        async: true,
					        success: function(resultAjax) {
					        	if(resultAjax.valid == 'false' || resultAjax.valid == false)
					        	{
					        		$('#myModalCSR #error_div').html(resultAjax.Message).show();
					        		return false;
					        	}
					        	else 
					        	{
					        		$('#myModalCSR #submitOrder #submit-button-popup').attr('disabled', 'disabled');
						        	$('#myModalCSR #submitOrder').removeAttr('onsubmit').submit();						        	
					        		return true;					        		
					        	}
					            
					        },
					        failure: function(errMsg) {
					            alert(errMsg);
					            return false;
					            
					        },
					        complete: function (){
					        	$('#loading-image').hide();
					        },
					        beforeSend : function(){
					        	$('#loading-image').show();
					        }
					    });
					    return false;
				}


				$('.upload').bind('change', function() {

					  //this.files[0].size gets the size of your file.
					  $('#file_name').html($(this).val());
					  $('#fileSize').html(this.files[0].size+' bytes');

					});


				$(document).ready(function() {
                $('#myModalCSR').on('shown.bs.modal', function(e) {
                    $('#csr_email_address').focus();
                });

				$('#myModal').on('show.bs.modal', function(e) {
				    var desc = atob($(e.relatedTarget).data('description'));
				    var platid = $(e.relatedTarget).data('platid');
				    var filename = $(e.relatedTarget).data('filename');
				    var filesize = $(e.relatedTarget).data('filesize');
				    var orderNo = $(e.relatedTarget).data('orderno');
						$('#order_description').val($.trim(desc));
						$('#plat_attach_id').val(platid);
						$('#plat_order_id').val(orderNo);
						$('#filetoShow').html(filename);
						$('#fileSizeToShow').html(filesize);


				});


					$( "#update_desc_form" ).submit(function( event ) {
						event.preventDefault();
						var PLAT_ATTACH_NO='';
						var PLAT_ORDER_NO='';
						 var PLAT_DESCRIPTION='';

						PLAT_ATTACH_NO = $('#plat_attach_id').val();
						PLAT_ORDER_NO = $('#plat_order_id').val();
						PLAT_DESCRIPTION = $('#order_description').val();

					 $.ajax({
						url: '/user/update-order-attachment-description',
				        type: "POST",
				        data: {'PLAT_ATTACH_NO':PLAT_ATTACH_NO, 'PLAT_ORDER_NO' : PLAT_ORDER_NO,'PLAT_DESCRIPTION' : PLAT_DESCRIPTION},
				      //  dataType: "json",
				        async: true,
				        success: function(resultAjax) {
				        	 window.location = '/user/review-order/Attachments';
				            return false;
				        },
				        failure: function(errMsg) {
				            alert(errMsg);
				        },
				        complete: function (){
				        	$('#loading-image').hide();
				        }
				    });

					});

				});
		 </script>


 <!-- Trigger the modal with a button -->
			<!-- Modal -->
			<div id="myModal" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!-- Modal content-->
			    <div class="modal-content">
			    <form role="form" id="update_desc_form" name="updateFormDesc">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal">&times;</button>
			        <h4 class="modal-title" style="color:#000080">Attachment File Details</h4>
			      </div>
			      <div class="modal-body">
			      <p>File Name: <strong id="filetoShow"></strong></p>
					<p>File size: <strong id="fileSizeToShow"></strong> <strong> bytes</strong> </p>

			    <div class="form-group">
			      	<label for="comment">File Description:</label>
			     	 <textarea class="form-control" rows="5" id="order_description"  maxlength="450"></textarea>
			    </div>

			    <div class="form-group">

			     	 <input type="hidden" class="form-control" id="plat_attach_id" value="">
			     	 <input type="hidden" class="form-control" id="plat_order_id" value="">
			    </div>

			      </div>
			      <div class="modal-footer">
			       <button class="btn btn-default submits-brn" type="submit">Save</button>
			        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>


			      </div>
			       </form>
			    </div>

			  </div>
			</div>
			
			<div id="myModalCSR" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!-- Modal content-->
			    <div class="modal-content text-center">
			         <?php 
			         $formOrderSubmit->setAttribute ( 'action', $this->url('user/reviewOrder', array('controller' => 'user', 'action' => 'review-order')));
			         $formOrderSubmit->setAttribute ( 'id', 'submitOrder' );
			         $formOrderSubmit->setAttribute ( 'onSubmit', 'return checkValuesSubmitOrderCSR()' );
			         $formOrderSubmit->prepare ();
			         echo $this->form ()->openTag ( $formOrderSubmit );
			         
			         ?>
			         <div class="alert alert-danger margin-top10" id="error_div" style="display:none;"></div>
			         <div class="margin-top20"> <em> You can enter one or more email addresses to receive a copy of the order details:</em></div>
                		  
							<fieldset class="row col-xs-10 col-xs-offset-1">
							
								<span class="" style="height:inherit;">
									<?php  echo $this->formRow ( $formOrderSubmit->get ( 'csr_email_address' ) ); ?>
								</span>
								
							</fieldset>
							<div class="clearfix"></div>
							<ul>
								  <li>You can enter multiple email addresses (max 2500 characters).</li>
								  <li>Separate each email address by comma.</li>
								  
								</ul>
								<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancel Submit</button>
						<?php echo $this->formrow( $formOrderSubmit->get('save')->setAttribute('id', 'submit-button-popup') ); ?> </div>
						<?php echo $this->form ()->closeTag(); ?>	
			    </div>

			  </div>
			</div>
 <script type="text/javascript">
		$( ".download-files-word" ).hover(function() {
			var id = $(this).data('id');
			$('#tool-tipfile'+id).popover({html:true});
			
			$('#tool-tipfile'+id).popover('toggle');
			var height_pop;
			var height_pop1;
		});
		
		$( ".download-files-word" ).mouseout(function() {
		
			
		//$('#dynamic_change_heigt').css('height', '0px');	
		});
		if(sessionStorage.getItem('emailRem')){
		$("input[name=PLU_EMAIL]").val(sessionStorage.getItem('emailRem'));
		}
		
		$( "input[name=PLU_EMAIL]" ).change(function() {
			 sessionStorage.setItem('emailRem',$(this).val());
			});

		

		$(document).keydown(function(e) {
		    // ESCAPE key pressed
		    if (e.keyCode == 27) {
		    	$('.bootbox-close-button').trigger('click');
		    }
		});
</script>