            <div class="csr col-md-12 col-sm-12 col-xs-12">
             	<div class="csr-heading text-center">User Details</div>
				<div class="clearfix"></div>
				<h1 class="csr-top-link">Add a PolarLink User <!--<a href=""><i class="fa fa-angle-left"></i>&nbsp;Back to List of Announcements</a>--></h1>
				<div class="clearfix"></div>
                <div class="item-search-tabs">
					<div class="ordering-option tab-content margin-top30 padding-none">
						<h2 class="heading">User Details</h2>
						<form class="col-md-10 pdding-responsive form-signin login-form information-form text-center-responsive">
							<fieldset class="col-md-12">
								<label for="inputEmail">Customer:</label> <span class="normal-text">123456 - Adirondack Beverage-Privt Lbl</span>
							</fieldset>
							<fieldset class="col-md-12">
								<label for="inputEmail">User ID</label> 
								<input type="text" value="Jvalance" />
							</fieldset>
							<fieldset class="col-md-12">
								<label for="inputEmail">First Name:</label> 
								<input type="text" value="John" />
							</fieldset>
							<fieldset class="col-md-12">
								<label for="inputEmail">Last Name:</label> 
								<input type="text" value="Valance" />
							</fieldset>
							<fieldset class="col-md-12">
								<label for="inputEmail">Password:</label> 
								<input type="password" value="***************" />
								<a class="change-password" href="javascript:void(0);">Change Password</a>
							</fieldset>
							<fieldset class="col-md-12">
								<label>PolarLink Status:</label>
								<select>
									<option>Enabled</option>
								</select>
							</fieldset>
							<fieldset class="col-md-12">
								<label for="inputPassword">Email Address:</label>
								<input type="text" value="johnv@jvalance.com" />
							</fieldset>
							<fieldset class="col-md-12">
								<div class="width28per pull-left">&nbsp;</div>
								<div class="width72per pull-left"> 
									<div class="user-details-checkbox"> 
										<div class="pull-left width32per"> 
											<input type="checkbox" class="view-as-user-margin9" />
											<label>Polar Beverage CSR?</label>
										</div>
										<div class="pull-left width60per margin-left10"> 
											<input type="checkbox" class="view-as-user-margin9" />
											<label>PolarLink Customer/User Administrator?</label>
										</div>
									</div>
								</div>
							</fieldset>
						</form>
						<div class="clearfix"></div>
						<hr class="separator">
						<div class="clearfix"></div>
						<div class="col-md-12">
							<div class="order-heading margin-none">User's Defaults:</div>
							<form class="UsersDefaults col-md-12 form-signin login-form information-form text-center-responsive">
								<fieldset class="col-md-12">
									<label for="inputEmail">Ship-To:</label> 
									<span class="normal-text font-weight400">Adirondack Beverage-From Ga<br />
									701 Corporations Park<br />
									Scotia, Ny, 12302
									<a href="" class="change-text">Change</a></span>
								</fieldset>
								<fieldset class="col-md-12 margin-top20">
									<label for="inputEmail">Ship Method:</label> 
									<span class="normal-text font-weight400">
										<div class="method-list">
											<label class="btn btn-default active">Delivery with Backhaul</label>
											<label class="btn btn-default">Delivery no Backhaul</label>
											<label class="btn btn-default">Pick Up</label>
										</div>
									</span>
								</fieldset>
								<fieldset class="col-md-12 margin-top20">
									<label for="inputEmail">UOM:</label> 
									<span class="normal-text font-weight400">
										<div class="method-list">
											<label class="btn btn-default active">Pallets</label>
											<label class="btn btn-default">Cases</label>
											<label class="btn btn-default">Each</label>
										</div>
									</span>
								</fieldset>
							</form>
							<div class="clearfix"></div>
							<div class="type-message">
								<form class="UsersDefaults col-md-12 form-signin login-form information-form text-center-responsive">
								<fieldset class="col-md-12">
									<label for="inputEmail">Added:</label> 
									<span class="normal-text">Mar 1, 2015 at 10:24:03AM by Jvalance</span>
								</fieldset>
								<fieldset class="col-md-12">
									<label for="inputEmail">Changed:</label> 
									<span class="normal-text">May 10, 2015 at 12:19:45PM by Jvlance</span>
								</fieldset>
								<fieldset class="col-md-12">
									<label for="inputEmail">First Login:</label> 
									<span class="normal-text">Mar 2, 2015 at 9:03:22AM by Polarusr</span>
								</fieldset>
								<fieldset class="col-md-12">
									<label for="inputEmail">Last Login:</label> 
									<span class="normal-text">Mar 2, 2015 at 9:03:22AM by Polarusr</span>
								</fieldset>
							</form>
							</div>
						</div>
						<div class="clearfix"></div>
						<div class="buttons col-md-12">
							<button class="btn" type="submit">Save</button>
							<button class="btn" type="button">Cancel</button>
						</div>
						<p class="clearfix"></p>
					</div>
					<div class="clearfix"></div>
				</div>
             </div>
 
	<div id="change-password">
		<div class="popup">
			<div class="password-heading">Change Password <span class="close-popup"><i class="fa fa-times">&nbsp;</i></span></div>
			<form class="col-md-12 login-form change-password-popup-form">
				<fieldset class="col-md-12">
					<label>New Password:</label> 
					<input type="password" value="" />
				</fieldset>
				<fieldset class="col-md-12">
					<label>Confirm Password:</label> 
					<input type="password" value="" />
				</fieldset>
				<fieldset class="col-md-12">
					<label>&nbsp;</label> 
					<button class="btn" type="button"><i class="fa fa-floppy-o"></i>&nbsp;Save</button>
				</fieldset>
			</form>
		</div>
	</div>
<script type="text/javascript">
	function checkKeyUp(){
		$('.formShowHide input[name="quantity"]').keyup(function(e) {                                   
		if (e.keyCode == 13){ $(this).closest('form').find('button.submitInlineButtonAjax').trigger('click'); }     // enter
		if (e.keyCode == 27){ $(this).closest('form').find('button.cancelInlineButtonAjax').trigger('click'); } // esc
		});
	}
	checkKeyUp();
</script>
<script type="text/javascript">
	$('#change-password').hide()
	$("a.change-password").click(function(){
    $('#change-password').show()
});

$(".close-popup").click(function(){
    $('#change-password').hide()
});
</script>  
