SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","PLINKDEV" ;

CREATE OR REPLACE FUNCTION FN_CURRTIME6 ( ) 
	RETURNS DECIMAL(6, 0)   
	LANGUAGE SQL 
	SPECIFIC FN_CURRTIME6 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = PLINKDEV , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	RETURN DEC ( REPLACE ( CHAR ( CURRENT TIME ) , '.' , '' ) , 6 , 0 ) ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION FN_CURRTIME6 
TO JVALANCE ; 
  
;
