SET PATH *LIBL ;

CREATE OR REPLACE FUNCTION FN_DATEDEC8 ( 
	IN_DATE DATE ) 
	RETURNS DECIMAL(8, 0)   
	LANGUAGE SQL 
	SPECIFIC FN_DATEDEC8 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	RETURN DEC ( REPLACE ( CHAR ( IN_DATE , ISO ) , '-' , '' ) , 8 , 0 ) ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC FUNCTION FN_DATEDEC8 
TO JVALANCE ; 
  
;
