<?php 

/**
 * Bind Controller Variables
 *
 * @var string $env
 */

echo $this->doctype(); 

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Polar Link Ordering System')->setSeparator(' - ')->setAutoEscape(false); ?>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale = 1, maximum-scale=1">
        

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basepath('css/customer-ship-to.css'))
                        ->prependStylesheet($this->basepath('css/dashboard.css'))
                        ->prependStylesheet($this->basepath('css/reset.css'))
                        ->prependStylesheet($this->basePath('css/responsive.css'))
                        ->prependStylesheet($this->basePath('css/custom.css?v=' . time()))
                        ->prependStylesheet($this->basePath('css/build.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                         ?>

        <!-- Scripts -->
        <?php 
         echo $this->headScript()  
         ->prependFile($this->basePath('js/js-cookie.js'))
         ->prependFile($this->basePath('js/jquery.number.min.js'))
         ->prependFile($this->basePath('js/custom.js?v=' . time()))
         ->prependFile($this->basePath('js/bootbox.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
          
//        echo $this->headScript()
//            ->prependFile($this->basePath('js/bootstrap.min.js'))
//            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//        ;
        ?>

    </head>
    <body>
    <div id="loading-image" style="display:none;">
        <img src="<?php echo $this->basePath('img/ajax-loader.gif'); ?>" id="" style="display:block;"/>
</div>
    
     <div class="container">
   <div class="col-lg-12"> 
   		<div class="row header-group"> 
        	<div class="logo"> <img src="<?php echo $this->basePath('img/logo.png'); ?>"> </div>
                <div class="brand-name brand-name-inner-page">  <span>Polar Link Ordering System</span> <?php // echo '<pre>'; print_r($identity); die; 
         				if(($identity['PLU_POLAR_CSR'] == 'Y')){
							if(empty($identity['CUST_NAME']) || empty($identity['PLU_CUST_GROUP'])){
								 echo '(no customer selected)'; 
							 } else {
								echo 'CSR as: '.$identity['CUST_NAME']; 
								}
						} 
						else
						{
								echo $identity['CUST_NAME']; 
						} 
						?> </div>
                <div class="header-right-block">
                
            	<div class="mail-id">
            	
            		<?php if( $env && !(strcasecmp($env, 'PROD') === 0)):?>
            			<span class="environment"><?php echo $env ?></span>
            		<?php endif; ?>
            			
            	User ID: <?php echo (!empty($identity['PLU_USER_ID'])?$identity['PLU_USER_ID']:''); ?></div>
                <ul class="main-nav flright">
                	<li><a href="<?php if($identity['PLU_POLAR_CSR'] == 'Y'){ echo $this->url('user/csrIndex'); } else { echo $this->url('user/index'); } ?>" data-toggle="tooltip" data-placement="bottom" title="Home"><i class="fa fa-home" aria-hidden="true"></i>
                	</a></li>
                    <!--<li><a href="" data-toggle="dropdown" data-placement="bottom" title="Setting"><img src="<?php echo $this->basePath('img/menu_icon02.png'); ?>" alt="" /></a></li>-->
                    <?php
                    // check whether this user is a polar link csr or not
                    if($identity['PLU_POLAR_CSR'] != 'Y'){
						
						if($identity['PLU_PLINK_ADMIN'] == 'Y'){
                    ?>
	                    <li class="dropdown">
						    <button class="button_toggle" type="button" data-toggle="dropdown"><img src="<?php echo $this->basePath('img/menu_icon02.png'); ?>" alt="" />&nbsp; <span><i class="fa fa-caret-down"></i>
						    </span></button>
						    <ul class="dropdown-menu">
						      <li><a href="<?php echo $this->url('user/adminCustomerEdit', array('controller' => 'user', 'action' => 'admin-customer-edit', 'id' => trim($identity['PLU_CUST_GROUP']))); ?>">Edit Customer Settings</a></li>
						      <li><a href="<?php echo $this->url('user/adminCustomerView', array('controller' => 'user', 'action' => 'admin-customer-view', 'id' => trim($identity['PLU_CUST_GROUP']))); ?>">View Customer Settings</a></li>
						      <li><a href="<?php echo $this->url('user/csrUserList'); ?>">Manage Users and Their Settings</a></li>
						    </ul>
					  	</li>
				  	<?php 
						} else {
					// echo '<pre>'; print_r($identity); echo '</pre>';
					 ?>
						<li class="dropdown">
						    <button class="button_toggle" type="button" data-toggle="dropdown"><img src="<?php echo $this->basePath('img/menu_icon02.png'); ?>" alt="" />&nbsp; <span><i class="fa fa-caret-down"></i>
						    </span></button>
						    <ul class="dropdown-menu">
						      <li><a href="<?php echo $this->url('user/adminCustomerView', array('controller' => 'user', 'action' => 'admin-customer-view', 'id' => trim($identity['PLU_CUST_GROUP']))); ?>">View Customer Settings</a></li>
						      <li><a href="<?php echo $this->url('user/csrUserView', array('controller' => 'user', 'action' => 'csr-user-view', 'id' => trim($identity['PLU_USER_ID']))); ?>">View My Profile Settings</a></li>
						      <li><a href="<?php echo $this->url('user/csrUserEdit', array('controller' => 'user', 'action' => 'csr-user-edit', 'id' => trim($identity['PLU_USER_ID']))); ?>">Edit My Profile Settings</a></li>
						    </ul>
					  	</li>
					<?php 
						}
					} ?>
                    <li><a href="<?php echo $this->url('user/logout'); ?>" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="fa fa-sign-out" aria-hidden="true"></i>
                    </a></li>
                    <li><a href="" data-toggle="tooltip" data-placement="bottom" title="Help"><i class="fa fa-question-circle" aria-hidden="true"></i>
                    </a></li>
                </ul>
            </div>
        </div>
   </div>
   
   	<div class="col-md-12 col-sm-12 col-xs-12 inner-page-outer">
   	<?php if ($this->flashMessenger()->hasMessages() && !empty($loginResult)) { ?>

    <div class="alert alert-info<?php if($loginResult['result'] == '1'){ echo ' alert-success'; } else { echo ' alert-danger'; } ?>">
<?php
    $messages = $this->flashMessenger()->getMessages();
    foreach($messages as $message) {
        echo $message;
    } ?>

    </div>
<?php }

?>
            <?php  echo $this->content; ?>
            <div class="clearfix"></div>    
    <div class="col-md-12 col-sm-12 col-xs-12 footer-outer">
        <div class="copy-right text-center">
            &copy; Copyright Polar Beverages 2016 - <?php echo date('Y'); ?>. All rights reserved.
            <br />
            
            Website Powered By <a target="_blank" href="http://www.div1sys.com" title="Divison 1 Systems">Divison 1 Systems</a>   
            
        </div>
    </div>
            
    </div>
    
    
</div>   
        
       

        <?php  echo $this->inlineScript(); ?>
        
    </body>
</html>
