<div class="customer-selected">
	<span class="no-customer">No Customer Selected</span>
	Select a customer below to work with their orders.
</div>
<ul id="menu-ordering">
	<li style="float:left;">
		<a href="<?php echo $this->url('user/csrSelectCustomer');  ?>">
			<div class="fonts-icons">
				<span class="fa-stack fa-lg fonts-awesome menu-ordering-option"> <i
					class="fa fa-building-o fa-stack-2x"></i> <i
					class="fa fa-user font-size25"></i>
				</span>
			</div>
			<br/>
			<span class="menu-ordering-text">Select customer</span>
		</a>
	</li>
</ul>