SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_DELETE_ANNOUNCEMENT ( 
	IN IN_ANNOUNCEMENT_ID INTEGER , 
	OUT OUT_MESSAGE VARCHAR(100) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELETE_ANNOUNCEMENT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
/*================================================================================ 
Created Sept 2015 by John Valance 
Delete an announcement in the PLINK_ANNOUNCEMENTS table. 
=================================================================================*/ 
	DELETE FROM PLINK_ANNOUNCEMENTS 
	WHERE PLA_ID = IN_ANNOUNCEMENT_ID ; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_DELETE_ANNOUNCEMENT 
TO JVALANCE ; 
  
;
