SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_GET_REQUESTDATE ( 
	IN IN_CUSTNUM CHAR(8) , 
	IN IN_SHIPTO CHAR(4) , 
	IN IN_SCHEDULEDATE CHAR(8) , 
	IN IN_PU_DELIV CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GET_REQUESTDATE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
	DECLARE REQDATE CHAR ( 8 ) DEFAULT '        ' ; 
  
	DECLARE C1 CURSOR WITH RETURN FOR 
		SELECT IN_CUSTNUM , IN_SHIPTO , IN_SCHEDULEDATE , IN_PU_DELIV , REQDATE 
		FROM SYSIBM . SYSDUMMY1 ; 
  
	CALL REQDATE ( IN_CUSTNUM , IN_SHIPTO , IN_SCHEDULEDATE , IN_PU_DELIV , REQDATE ) ; 
  
	OPEN C1 ; 
	RETURN ; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_GET_REQUESTDATE 
TO JVALANCE ; 
  
;
