SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_SAVE_ANNOUNCEMENT ( 
	IN IN_USER_ID CHAR(15) , 
	IN IN_FACILITY CHAR(3) , 
	IN IN_CUST_TYPE CHAR(4) , 
	IN IN_START_DATE DATE , 
	IN IN_END_DATE DATE , 
	IN IN_MESSAGE VARCHAR(2500) , 
	OUT OUT_ID DECIMAL(10, 0) , 
	OUT OUT_MESSAGE VARCHAR(100) ) 
	LANGUAGE SQL 
	SPECIFIC SP_SAVE_ANNOUNCEMENT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
/*================================================================================ 
Created Sept 2015 by John Valance 
Insert an announcement into PLINK_ANNOUNCEMENTS table. 
=================================================================================*/ 
	INSERT INTO PLINK_ANNOUNCEMENTS ( 
		PLA_FACILITY , 
		PLA_CUST_TYPE , 
		PLA_START_DATE , 
		PLA_END_DATE , 
		PLA_MESSAGE , 
		PLA_CRT_TIME , 
		PLA_CRT_USER 
	) VALUES ( 
		IN_FACILITY , 
		IN_CUST_TYPE , 
		IN_START_DATE , 
		IN_END_DATE , 
		IN_MESSAGE , 
		CURRENT TIMESTAMP , 
		IN_USER_ID 
	) ; 
  
	SET OUT_ID = IDENTITY_VAL_LOCAL ( ) ; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_SAVE_ANNOUNCEMENT 
TO JVALANCE ; 
  
;
