SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_SAVE_ORDERSUBSTITUTEITEM ( 
	IN IN_ORDERNUM DECIMAL(8, 0) , 
	IN IN_ITEMNO CHAR(35) , 
	IN IN_ACTION CHAR(3) , 
	IN IN_USER VARCHAR(15) , 
	OUT OUT_SUBSCOUNT DECIMAL(3, 0) , 
	OUT OUT_RESULT CHAR(1) , 
	OUT OUT_MESSAGE VARCHAR(100) ) 
	LANGUAGE SQL 
	SPECIFIC SP_SAVE_ORDERSUBSTITUTEITEM 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
/*================================================================================ 
Created August 2015 by John Valance 
  
Save information entered on the Order Header page. 
=================================================================================*/ 
	DECLARE WK_ENTRYSTEP INTEGER ;	 
	DECLARE WK_DATE8 DEC ( 8 , 0 ) ; 
	DECLARE WK_TIME6 DEC ( 6 , 0 ) ; 
	DECLARE WK_SUBSCOUNT INTEGER ; 
	DECLARE WK_HIGHESTPRIORITY DEC ( 5 , 2 ) ; 
			 
	 -- Initialize work variables 
	SET OUT_MESSAGE = '' ; 
	SET OUT_RESULT = '1' ; 
	 
	 -- Get current date/time formatted values 
	SELECT FN_CURRDATE8 ( ) , FN_CURRTIME6 ( ) 
	INTO WK_DATE8 , WK_TIME6 
	FROM SYSIBM . SYSDUMMY1 ; 
	 
	IF IN_ACTION = 'UPD' THEN 
		UPDATE PLINK_SUBSTITUTES 
		SET PLS_PRIORITY = IN_PRIORITY , 
			PLS_CHG_TIME = CURRENT TIMESTAMP , 
			PLS_CHG_USER = IN_USER 
		WHERE PLS_ORDER_NO = IN_ORDERNUM 
		AND PLS_ITEM_NO = IN_ITEMNO ; 
	END IF ; 
	 
	IF IN_ACTION = 'RMV' THEN 
		DELETE FROM PLINK_SUBSTITUTES 
		WHERE PLS_ORDER_NO = IN_ORDERNUM 
		AND PLS_ITEM_NO = IN_ITEMNO ; 
	END IF ; 
	 
	IF IN_ACTION = 'ADD' THEN 
		SELECT MAX ( PLS_PRIORITY ) INTO WK_HIGHESTPRIORITY 
		FROM PLINK_SUBSTITUTES 
		WHERE PLS_ORDER_NO = IN_ORDERNUM ; 
		 
		IF WK_HIGHESTPRIORITY IS NULL THEN 
			SET WK_HIGHESTPRIORITY = 1 ; 
		ELSE 
			SET WK_HIGHESTPRIORITY = WK_HIGHESTPRIORITY + 1 ; 
		END IF ; 
		 
		INSERT INTO PLINK_SUBSTITUTES ( 
			PLS_ORDER_NO , 
			PLS_ITEM_NO , 
			PLS_PRIORITY , 
			PLS_CRT_TIME , 
			PLS_CRT_USER 
		) VALUES ( 
			IN_ORDERNUM , 
			IN_ITEMNO , 
			WK_HIGHESTPRIORITY , 
			CURRENT TIMESTAMP , 
			IN_USER 
		) ; 
	END IF ; 
	 
	SELECT COUNT ( * ) INTO WK_SUBSCOUNT 
	FROM PLINK_SUBSTITUTES 
	WHERE PLS_ORDER_NO = IN_ORDERNUM ; 
	 
	 --=============================================== 
	 -- DO FOLLOWING IF AT LEAST 3 SUBS SELECTED 
	 --=============================================== 
	IF WK_SUBSCOUNT >= 3 THEN 
		 -- Ensure last entry step is at least 4 (i.e., substitute items selected) 
		SELECT PLINK_ENTRY_STEP INTO WK_ENTRYSTEP 
			FROM ECH_PLNK WHERE HORD = IN_ORDERNUM ; 
		IF WK_ENTRYSTEP < 4 THEN 
			SET WK_ENTRYSTEP = 4 ; 
		END IF ; 
		 
		UPDATE ECH_PLNK SET 
			CHMNDT = WK_DATE8 , 
			CHMNTM = WK_TIME6 , 
			CHMNUS = IN_USER , 
			PLINK_ENTRY_STEP = WK_ENTRYSTEP 
		WHERE HORD = IN_ORDERNUM ; 
	END IF ; 
  
	SET OUT_SUBSCOUNT = WK_SUBSCOUNT ; 
	 
	RETURN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_SAVE_ORDERSUBSTITUTEITEM 
TO JVALANCE ; 
  
;
