SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_UTIL_QCMDEXC ( 
	IN IN_COMMANDSTR VARCHAR(1000) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UTIL_QCMDEXC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	DECLARE WK_STRLEN DEC ( 15 , 5 ) ; 
	 
	SET IN_COMMANDSTR = TRIM ( IN_COMMANDSTR ) ; 
	SET WK_STRLEN = LENGTH ( IN_COMMANDSTR ) ; 
	 
	CALL QCMDEXC ( IN_COMMANDSTR , WK_STRLEN ) ; 
	RETURN ; 
	 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_UTIL_QCMDEXC 
TO JVALANCE ; 
  
;
