SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_UPDATE_ANNOUNCEMENT ( 
	IN IN_ANNOUNCEMENT_ID INTEGER , 
	IN IN_USER_ID CHAR(15) , 
	IN IN_FACILITY CHAR(3) , 
	IN IN_CUST_TYPE CHAR(4) , 
	IN IN_START_DATE DATE , 
	IN IN_END_DATE DATE , 
	IN IN_MESSAGE VARCHAR(2500) , 
	OUT OUT_MESSAGE VARCHAR(100) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UPDATE_ANNOUNCEMENT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
/*================================================================================ 
Created Sept 2015 by John Valance 
Update an announcement in the PLINK_ANNOUNCEMENTS table. 
=================================================================================*/ 
	UPDATE PLINK_ANNOUNCEMENTS 
	SET 
		PLA_FACILITY = IN_FACILITY , 
		PLA_CUST_TYPE = IN_CUST_TYPE , 
		PLA_START_DATE = IN_START_DATE , 
		PLA_END_DATE = IN_END_DATE , 
		PLA_MESSAGE = IN_MESSAGE , 
		PLA_CHG_TIME = CURRENT TIMESTAMP , 
		PLA_CHG_USER = IN_USER_ID 
	WHERE PLA_ID = IN_ANNOUNCEMENT_ID 
	; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_UPDATE_ANNOUNCEMENT 
TO JVALANCE ; 
  
;
