SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SP_UPDATE_PLINK_USER ( 
	IN IN_PLU_USER_ID CHAR(15) , 
	IN IN_PLU_FIRST_NAME VARCHAR(30) , 
	IN IN_PLU_LAST_NAME VARCHAR(40) , 
	IN IN_PLU_PASSWORD VARCHAR(60) , 
	IN IN_PLU_CUSTNO DECIMAL(8, 0) , 
	IN IN_PLU_DFT_UOM CHAR(2) , 
	IN IN_PLU_DFT_SHIPTO DECIMAL(4, 0) , 
	IN IN_PLU_DFT_SHIP_METHOD CHAR(1) , 
	IN IN_PLU_POLAR_CSR CHAR(1) , 
	IN IN_PLU_PLINK_ADMIN CHAR(1) , 
	IN IN_PLU_STATUS CHAR(1) , 
	IN IN_PLU_EMAIL_ADDRESS VARCHAR(100) , 
	IN IN_PLU_CHG_USER CHAR(10) , 
	OUT OUT_MESSAGE VARCHAR(100) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UPDATE_PLINK_USER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
/*================================================================================ 
Created November 2015 by John Valance 
Delete an announcement in the PLINK_ANNOUNCEMENTS table. 
=================================================================================*/ 
	SET OUT_MESSAGE = '' ; 
	 
	IF NOT EXISTS ( SELECT * FROM PLINK_USER WHERE PLU_USER_ID = IN_PLU_USER_ID ) THEN 
		SET OUT_MESSAGE = 
			'Record not updated: User ID ' 
			|| TRIM ( IN_PLU_USER_ID ) 
			|| ' not found in the PolarLink Users table.' ; 
		RETURN ; 
	ELSE 
		UPDATE PLINK_USER SET 
		 
			PLU_FIRST_NAME = IN_PLU_FIRST_NAME , 
			PLU_LAST_NAME = IN_PLU_LAST_NAME , 
			PLU_PASSWORD = IN_PLU_PASSWORD , 
			PLU_CUSTNO = IN_PLU_CUSTNO , 
			PLU_DFT_UOM = IN_PLU_DFT_UOM , 
			PLU_DFT_SHIPTO = IN_PLU_DFT_SHIPTO , 
			PLU_DFT_SHIP_METHOD = IN_PLU_DFT_SHIP_METHOD , 
			PLU_POLAR_CSR = IN_PLU_POLAR_CSR , 
			PLU_PLINK_ADMIN = IN_PLU_PLINK_ADMIN , 
			PLU_STATUS = IN_PLU_STATUS , 
			PLU_EMAIL_ADDRESS = IN_PLU_EMAIL_ADDRESS , 
			PLU_CHG_TIME = CURRENT TIMESTAMP , 
			PLU_CHG_USER = IN_PLU_CHG_USER 
		 
		WHERE PLU_USER_ID = IN_PLU_USER_ID ; 
	END IF ; 
	 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SP_UPDATE_PLINK_USER 
TO JVALANCE ; 
  
;
