SET PATH *LIBL ;

CREATE OR REPLACE PROCEDURE SPE_PALLADD_R ( 
	IN ORDERNUM CHAR(8) ) 
	LANGUAGE RPGLE 
	SPECIFIC SPE_PALLADD_R 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'PLINKPRD/PALLADD_R' 
	PARAMETER STYLE GENERAL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SPE_PALLADD_R 
TO JVALANCE ; 
  
;
