
--DROP TABLE VGFILES/SRVYCNVBAT;

CREATE TABLE VGFILES/SRVYCNVBAT (
	CB_BATCHNO FOR COLUMN CBBATCHNO
	INTEGER GENERATED ALWAYS AS IDENTITY (
	START WITH 1 INCREMENT BY 1
	NO MINVALUE NO MAXVALUE
	NO CYCLE NO ORDER
	CACHE 20 )
	,
	CB_RUNDATE FOR COLUMN CBRUNDATE  DATE DEFAULT NULL ,
	CB_RUNTIME FOR COLUMN CBRUNTIME  TIME DEFAULT NULL ,
	CB_COUNT FOR COLUMN CBCOUNT    INTEGER DEFAULT NULL ,
	CB_MAILDATE FOR COLUMN CBMAILDATE  DATE DEFAULT NULL ,
	CB_MAILTIME FOR COLUMN CBMAILTIME  TIME DEFAULT NULL ,
	CB_MAILTO FOR COLUMN CBMAILTO  varchar(250) DEFAULT NULL ,
	CB_STATUS FOR COLUMN CBSTATUS   CHAR(10) CCSID 37 DEFAULT NULL ,
	CB_STARTDATE FOR COLUMN STARTDATE  DATE DEFAULT NULL ,
	CB_ENDDATE FOR COLUMN ENDDATE    DATE DEFAULT NULL
) ;

ALTER TABLE VGFILES/SRVYCNVBAT
	ADD CONSTRAINT VGFILES/SRVYCNVBATL1
	UNIQUE( CB_BATCHNO ) ;

LABEL ON TABLE VGFILES/SRVYCNVBAT
	IS 'Cust conversion survey batch header' ;

LABEL ON COLUMN VGFILES/SRVYCNVBAT
( CB_BATCHNO IS 'Survey              batch#' ,
	CB_RUNDATE IS 'Survey batch        run date' ,
	CB_RUNTIME IS 'Survey batch        run time' ,
	CB_COUNT IS 'Survey batch        record              count' ,
	CB_STATUS    IS 'Survey              batch               status' ,
	CB_STARTDATE IS 'Start               Date' ,
	CB_ENDDATE IS 'End                 Date'
) ;

LABEL ON COLUMN VGFILES/SRVYCNVBAT
( CB_BATCHNO TEXT IS 'Survey batch number' ,
	CB_RUNDATE TEXT IS 'Survey batch run date' ,
	CB_RUNTIME TEXT IS 'Survey batch run time' ,
	CB_MAILDATE TEXT IS 'Date emailed to service bureau' ,
	CB_MAILTIME TEXT IS 'Time emailed to service bureau' ,
	CB_MAILTO TEXT IS 'Email address sent to' ,
    CB_COUNT TEXT IS 'Survey batch record count' ,
	CB_STATUS TEXT IS 'Survey batch process status' ,
	CB_STARTDATE TEXT IS 'Selection Start date' ,
	CB_ENDDATE TEXT IS 'Selection end date'
) ;

