--  Generate SQL
--  Version:                   	V5R3M0 040528
--  Generated on:              	10/25/07 19:44:03
--  Relational Database:       	S650994F
--  Standards Option:          	DB2 UDB iSeries

CREATE TABLE VGFILES/WEBUSELOG (
	WBACCOUNTNO FOR COLUMN WBACCT DECIMAL(7, 0) DEFAULT NULL ,
	WBDATETIME FOR COLUMN WBTIME  TIMESTAMP DEFAULT NULL ,
	WBIPADDRESS FOR COLUMN WBIPADDR   CHAR(15) CCSID 37 DEFAULT NULL ,
	WBSCRIPTNAME FOR COLUMN WBSCRIPT   VARCHAR(100) CCSID 37 DEFAULT NULL ,
	WBBROWSER VARCHAR(1000) CCSID 37 DEFAULT NULL ,
	WBSESSIONID FOR COLUMN WBSESSID   VARCHAR(50) CCSID 37 DEFAULT NULL ,
	WBLOGIN CHAR(1) CCSID 37 DEFAULT NULL ,
	WBVIEWYEAR CHAR(4) CCSID 37 DEFAULT NULL ) ;

LABEL ON TABLE VGFILES/WEBUSELOG
	IS 'Web account access usage log' ;

LABEL ON COLUMN VGFILES/WEBUSELOG
( WBACCOUNTNO IS 'Acct                No' ,
	WBDATETIME IS 'Access              Date/Time' ,
	WBIPADDRESS IS 'Remote              IP Address' ,
	WBSCRIPTNAME IS 'PHP Script           ' ,
	WBBROWSER IS 'Browser              ' ,
	WBSESSIONID IS 'Session ID           ' ,
	WBLOGIN IS 'Login?               ' ,
	WBVIEWYEAR IS 'Year                Viewed' ) ;

LABEL ON COLUMN VGFILES/WEBUSELOG
( WBACCOUNTNO TEXT IS 'Account Number' ,
	WBDATETIME TEXT IS 'Access Timestamp' ,
	WBIPADDRESS TEXT IS 'Remote IP Address' ,
	WBSCRIPTNAME TEXT IS 'PHP Script Name' ,
	WBBROWSER TEXT IS 'Browser (User Agent)' ,
	WBSESSIONID TEXT IS 'Session ID' ,
	WBLOGIN TEXT IS 'Login action? (Y or blank)' ,
	WBVIEWYEAR TEXT IS 'Viewed year' ) ;
